// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: grpc/tests.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TestService_WithError_FullMethodName = "/grpc.TestService/WithError"
	TestService_WithPanic_FullMethodName = "/grpc.TestService/WithPanic"
	TestService_Do_FullMethodName        = "/grpc.TestService/Do"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	WithError(ctx context.Context, in *WithErrorRequest, opts ...grpc.CallOption) (*WithErrorResponse, error)
	WithPanic(ctx context.Context, in *WithPanicRequest, opts ...grpc.CallOption) (*WithPanicResponse, error)
	Do(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) WithError(ctx context.Context, in *WithErrorRequest, opts ...grpc.CallOption) (*WithErrorResponse, error) {
	out := new(WithErrorResponse)
	err := c.cc.Invoke(ctx, TestService_WithError_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) WithPanic(ctx context.Context, in *WithPanicRequest, opts ...grpc.CallOption) (*WithPanicResponse, error) {
	out := new(WithPanicResponse)
	err := c.cc.Invoke(ctx, TestService_WithPanic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) Do(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, TestService_Do_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	WithError(context.Context, *WithErrorRequest) (*WithErrorResponse, error)
	WithPanic(context.Context, *WithPanicRequest) (*WithPanicResponse, error)
	Do(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) WithError(context.Context, *WithErrorRequest) (*WithErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithError not implemented")
}
func (UnimplementedTestServiceServer) WithPanic(context.Context, *WithPanicRequest) (*WithPanicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithPanic not implemented")
}
func (UnimplementedTestServiceServer) Do(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_WithError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).WithError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_WithError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).WithError(ctx, req.(*WithErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_WithPanic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithPanicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).WithPanic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_WithPanic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).WithPanic(ctx, req.(*WithPanicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_Do_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Do(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WithError",
			Handler:    _TestService_WithError_Handler,
		},
		{
			MethodName: "WithPanic",
			Handler:    _TestService_WithPanic_Handler,
		},
		{
			MethodName: "Do",
			Handler:    _TestService_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/tests.proto",
}
