// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: grpc/tests.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithErrorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WithErrorRequest) Reset() {
	*x = WithErrorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tests_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithErrorRequest) ProtoMessage() {}

func (x *WithErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tests_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithErrorRequest.ProtoReflect.Descriptor instead.
func (*WithErrorRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tests_proto_rawDescGZIP(), []int{0}
}

type WithErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WithErrorResponse) Reset() {
	*x = WithErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tests_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithErrorResponse) ProtoMessage() {}

func (x *WithErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tests_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithErrorResponse.ProtoReflect.Descriptor instead.
func (*WithErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tests_proto_rawDescGZIP(), []int{1}
}

type WithPanicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WithPanicRequest) Reset() {
	*x = WithPanicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tests_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithPanicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithPanicRequest) ProtoMessage() {}

func (x *WithPanicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tests_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithPanicRequest.ProtoReflect.Descriptor instead.
func (*WithPanicRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tests_proto_rawDescGZIP(), []int{2}
}

type WithPanicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WithPanicResponse) Reset() {
	*x = WithPanicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tests_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithPanicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithPanicResponse) ProtoMessage() {}

func (x *WithPanicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tests_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithPanicResponse.ProtoReflect.Descriptor instead.
func (*WithPanicResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tests_proto_rawDescGZIP(), []int{3}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tests_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tests_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_tests_proto_rawDescGZIP(), []int{4}
}

var File_grpc_tests_proto protoreflect.FileDescriptor

var file_grpc_tests_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x12, 0x0a, 0x10, 0x57, 0x69, 0x74, 0x68,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11,
	0x57, 0x69, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x12, 0x0a, 0x10, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x6e, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x6e,
	0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x32, 0xaf, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x57, 0x69, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x57, 0x69, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x6e, 0x69, 0x63,
	0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x6e, 0x69,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x6e, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x20, 0x0a, 0x02, 0x44, 0x6f, 0x12, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x6b, 0x69, 0x74, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_tests_proto_rawDescOnce sync.Once
	file_grpc_tests_proto_rawDescData = file_grpc_tests_proto_rawDesc
)

func file_grpc_tests_proto_rawDescGZIP() []byte {
	file_grpc_tests_proto_rawDescOnce.Do(func() {
		file_grpc_tests_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_tests_proto_rawDescData)
	})
	return file_grpc_tests_proto_rawDescData
}

var file_grpc_tests_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_tests_proto_goTypes = []interface{}{
	(*WithErrorRequest)(nil),  // 0: grpc.WithErrorRequest
	(*WithErrorResponse)(nil), // 1: grpc.WithErrorResponse
	(*WithPanicRequest)(nil),  // 2: grpc.WithPanicRequest
	(*WithPanicResponse)(nil), // 3: grpc.WithPanicResponse
	(*Empty)(nil),             // 4: grpc.Empty
}
var file_grpc_tests_proto_depIdxs = []int32{
	0, // 0: grpc.TestService.WithError:input_type -> grpc.WithErrorRequest
	2, // 1: grpc.TestService.WithPanic:input_type -> grpc.WithPanicRequest
	4, // 2: grpc.TestService.Do:input_type -> grpc.Empty
	1, // 3: grpc.TestService.WithError:output_type -> grpc.WithErrorResponse
	3, // 4: grpc.TestService.WithPanic:output_type -> grpc.WithPanicResponse
	4, // 5: grpc.TestService.Do:output_type -> grpc.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_tests_proto_init() }
func file_grpc_tests_proto_init() {
	if File_grpc_tests_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_tests_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithErrorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tests_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tests_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithPanicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tests_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithPanicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tests_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_tests_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tests_proto_goTypes,
		DependencyIndexes: file_grpc_tests_proto_depIdxs,
		MessageInfos:      file_grpc_tests_proto_msgTypes,
	}.Build()
	File_grpc_tests_proto = out.File
	file_grpc_tests_proto_rawDesc = nil
	file_grpc_tests_proto_goTypes = nil
	file_grpc_tests_proto_depIdxs = nil
}
