// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewBatchWorker creates a new instance of BatchWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchWorker[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchWorker[T] {
	mock := &BatchWorker[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BatchWorker is an autogenerated mock type for the Worker type
type BatchWorker[T any] struct {
	mock.Mock
}

type BatchWorker_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *BatchWorker[T]) EXPECT() *BatchWorker_Expecter[T] {
	return &BatchWorker_Expecter[T]{mock: &_m.Mock}
}

// Close provides a mock function for the type BatchWorker
func (_mock *BatchWorker[T]) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// BatchWorker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type BatchWorker_Close_Call[T any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx
func (_e *BatchWorker_Expecter[T]) Close(ctx interface{}) *BatchWorker_Close_Call[T] {
	return &BatchWorker_Close_Call[T]{Call: _e.mock.On("Close", ctx)}
}

func (_c *BatchWorker_Close_Call[T]) Run(run func(ctx context.Context)) *BatchWorker_Close_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *BatchWorker_Close_Call[T]) Return() *BatchWorker_Close_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *BatchWorker_Close_Call[T]) RunAndReturn(run func(ctx context.Context)) *BatchWorker_Close_Call[T] {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type BatchWorker
func (_mock *BatchWorker[T]) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// BatchWorker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type BatchWorker_Start_Call[T any] struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx
func (_e *BatchWorker_Expecter[T]) Start(ctx interface{}) *BatchWorker_Start_Call[T] {
	return &BatchWorker_Start_Call[T]{Call: _e.mock.On("Start", ctx)}
}

func (_c *BatchWorker_Start_Call[T]) Run(run func(ctx context.Context)) *BatchWorker_Start_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *BatchWorker_Start_Call[T]) Return() *BatchWorker_Start_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *BatchWorker_Start_Call[T]) RunAndReturn(run func(ctx context.Context)) *BatchWorker_Start_Call[T] {
	_c.Run(run)
	return _c
}

// Write provides a mock function for the type BatchWorker
func (_mock *BatchWorker[T]) Write(ctx context.Context, item *T) {
	_mock.Called(ctx, item)
	return
}

// BatchWorker_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type BatchWorker_Write_Call[T any] struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx
//   - item
func (_e *BatchWorker_Expecter[T]) Write(ctx interface{}, item interface{}) *BatchWorker_Write_Call[T] {
	return &BatchWorker_Write_Call[T]{Call: _e.mock.On("Write", ctx, item)}
}

func (_c *BatchWorker_Write_Call[T]) Run(run func(ctx context.Context, item *T)) *BatchWorker_Write_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*T))
	})
	return _c
}

func (_c *BatchWorker_Write_Call[T]) Return() *BatchWorker_Write_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *BatchWorker_Write_Call[T]) RunAndReturn(run func(ctx context.Context, item *T)) *BatchWorker_Write_Call[T] {
	_c.Run(run)
	return _c
}

// NewBatchWriter creates a new instance of BatchWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchWriter[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchWriter[T] {
	mock := &BatchWriter[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BatchWriter is an autogenerated mock type for the Writer type
type BatchWriter[T any] struct {
	mock.Mock
}

type BatchWriter_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *BatchWriter[T]) EXPECT() *BatchWriter_Expecter[T] {
	return &BatchWriter_Expecter[T]{mock: &_m.Mock}
}

// Write provides a mock function for the type BatchWriter
func (_mock *BatchWriter[T]) Write(ctx context.Context, items []*T) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*T) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BatchWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type BatchWriter_Write_Call[T any] struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx
//   - items
func (_e *BatchWriter_Expecter[T]) Write(ctx interface{}, items interface{}) *BatchWriter_Write_Call[T] {
	return &BatchWriter_Write_Call[T]{Call: _e.mock.On("Write", ctx, items)}
}

func (_c *BatchWriter_Write_Call[T]) Run(run func(ctx context.Context, items []*T)) *BatchWriter_Write_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*T))
	})
	return _c
}

func (_c *BatchWriter_Write_Call[T]) Return(err error) *BatchWriter_Write_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *BatchWriter_Write_Call[T]) RunAndReturn(run func(ctx context.Context, items []*T) error) *BatchWriter_Write_Call[T] {
	_c.Call.Return(run)
	return _c
}
