// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/centrifugal/centrifuge-go"
	mock "github.com/stretchr/testify/mock"
	"github.com/zloevil/jet/centrifugo/proto"
)

// NewCentrifugoClient creates a new instance of CentrifugoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCentrifugoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CentrifugoClient {
	mock := &CentrifugoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CentrifugoClient is an autogenerated mock type for the Client type
type CentrifugoClient struct {
	mock.Mock
}

type CentrifugoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CentrifugoClient) EXPECT() *CentrifugoClient_Expecter {
	return &CentrifugoClient_Expecter{mock: &_m.Mock}
}

// ClientId provides a mock function for the type CentrifugoClient
func (_mock *CentrifugoClient) ClientId() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClientId")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CentrifugoClient_ClientId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientId'
type CentrifugoClient_ClientId_Call struct {
	*mock.Call
}

// ClientId is a helper method to define mock.On call
func (_e *CentrifugoClient_Expecter) ClientId() *CentrifugoClient_ClientId_Call {
	return &CentrifugoClient_ClientId_Call{Call: _e.mock.On("ClientId")}
}

func (_c *CentrifugoClient_ClientId_Call) Run(run func()) *CentrifugoClient_ClientId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CentrifugoClient_ClientId_Call) Return(s string) *CentrifugoClient_ClientId_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CentrifugoClient_ClientId_Call) RunAndReturn(run func() string) *CentrifugoClient_ClientId_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type CentrifugoClient
func (_mock *CentrifugoClient) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CentrifugoClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type CentrifugoClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CentrifugoClient_Expecter) Close(ctx interface{}) *CentrifugoClient_Close_Call {
	return &CentrifugoClient_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *CentrifugoClient_Close_Call) Run(run func(ctx context.Context)) *CentrifugoClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CentrifugoClient_Close_Call) Return(err error) *CentrifugoClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CentrifugoClient_Close_Call) RunAndReturn(run func(ctx context.Context) error) *CentrifugoClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type CentrifugoClient
func (_mock *CentrifugoClient) Connect(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CentrifugoClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type CentrifugoClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *CentrifugoClient_Expecter) Connect(ctx interface{}, token interface{}) *CentrifugoClient_Connect_Call {
	return &CentrifugoClient_Connect_Call{Call: _e.mock.On("Connect", ctx, token)}
}

func (_c *CentrifugoClient_Connect_Call) Run(run func(ctx context.Context, token string)) *CentrifugoClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CentrifugoClient_Connect_Call) Return(err error) *CentrifugoClient_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CentrifugoClient_Connect_Call) RunAndReturn(run func(ctx context.Context, token string) error) *CentrifugoClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Connected provides a mock function for the type CentrifugoClient
func (_mock *CentrifugoClient) Connected() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CentrifugoClient_Connected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connected'
type CentrifugoClient_Connected_Call struct {
	*mock.Call
}

// Connected is a helper method to define mock.On call
func (_e *CentrifugoClient_Expecter) Connected() *CentrifugoClient_Connected_Call {
	return &CentrifugoClient_Connected_Call{Call: _e.mock.On("Connected")}
}

func (_c *CentrifugoClient_Connected_Call) Run(run func()) *CentrifugoClient_Connected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CentrifugoClient_Connected_Call) Return(b bool) *CentrifugoClient_Connected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CentrifugoClient_Connected_Call) RunAndReturn(run func() bool) *CentrifugoClient_Connected_Call {
	_c.Call.Return(run)
	return _c
}

// OnPublication provides a mock function for the type CentrifugoClient
func (_mock *CentrifugoClient) OnPublication(ctx context.Context, handler func(p centrifuge.ServerPublicationEvent) error) error {
	ret := _mock.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for OnPublication")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(p centrifuge.ServerPublicationEvent) error) error); ok {
		r0 = returnFunc(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CentrifugoClient_OnPublication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPublication'
type CentrifugoClient_OnPublication_Call struct {
	*mock.Call
}

// OnPublication is a helper method to define mock.On call
//   - ctx context.Context
//   - handler func(p centrifuge.ServerPublicationEvent) error
func (_e *CentrifugoClient_Expecter) OnPublication(ctx interface{}, handler interface{}) *CentrifugoClient_OnPublication_Call {
	return &CentrifugoClient_OnPublication_Call{Call: _e.mock.On("OnPublication", ctx, handler)}
}

func (_c *CentrifugoClient_OnPublication_Call) Run(run func(ctx context.Context, handler func(p centrifuge.ServerPublicationEvent) error)) *CentrifugoClient_OnPublication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(p centrifuge.ServerPublicationEvent) error
		if args[1] != nil {
			arg1 = args[1].(func(p centrifuge.ServerPublicationEvent) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CentrifugoClient_OnPublication_Call) Return(err error) *CentrifugoClient_OnPublication_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CentrifugoClient_OnPublication_Call) RunAndReturn(run func(ctx context.Context, handler func(p centrifuge.ServerPublicationEvent) error) error) *CentrifugoClient_OnPublication_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type CentrifugoClient
func (_mock *CentrifugoClient) Subscribe(ctx context.Context, token string, channel string, handler func(p centrifuge.Publication) error) error {
	ret := _mock.Called(ctx, token, channel, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, func(p centrifuge.Publication) error) error); ok {
		r0 = returnFunc(ctx, token, channel, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CentrifugoClient_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type CentrifugoClient_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - channel string
//   - handler func(p centrifuge.Publication) error
func (_e *CentrifugoClient_Expecter) Subscribe(ctx interface{}, token interface{}, channel interface{}, handler interface{}) *CentrifugoClient_Subscribe_Call {
	return &CentrifugoClient_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, token, channel, handler)}
}

func (_c *CentrifugoClient_Subscribe_Call) Run(run func(ctx context.Context, token string, channel string, handler func(p centrifuge.Publication) error)) *CentrifugoClient_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 func(p centrifuge.Publication) error
		if args[3] != nil {
			arg3 = args[3].(func(p centrifuge.Publication) error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CentrifugoClient_Subscribe_Call) Return(err error) *CentrifugoClient_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CentrifugoClient_Subscribe_Call) RunAndReturn(run func(ctx context.Context, token string, channel string, handler func(p centrifuge.Publication) error) error) *CentrifugoClient_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewCentrifugoServer creates a new instance of CentrifugoServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCentrifugoServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CentrifugoServer {
	mock := &CentrifugoServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CentrifugoServer is an autogenerated mock type for the Server type
type CentrifugoServer struct {
	mock.Mock
}

type CentrifugoServer_Expecter struct {
	mock *mock.Mock
}

func (_m *CentrifugoServer) EXPECT() *CentrifugoServer_Expecter {
	return &CentrifugoServer_Expecter{mock: &_m.Mock}
}

// BatchPublish provides a mock function for the type CentrifugoServer
func (_mock *CentrifugoServer) BatchPublish(ctx context.Context, channels []string, msg any) error {
	ret := _mock.Called(ctx, channels, msg)

	if len(ret) == 0 {
		panic("no return value specified for BatchPublish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, any) error); ok {
		r0 = returnFunc(ctx, channels, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CentrifugoServer_BatchPublish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchPublish'
type CentrifugoServer_BatchPublish_Call struct {
	*mock.Call
}

// BatchPublish is a helper method to define mock.On call
//   - ctx context.Context
//   - channels []string
//   - msg any
func (_e *CentrifugoServer_Expecter) BatchPublish(ctx interface{}, channels interface{}, msg interface{}) *CentrifugoServer_BatchPublish_Call {
	return &CentrifugoServer_BatchPublish_Call{Call: _e.mock.On("BatchPublish", ctx, channels, msg)}
}

func (_c *CentrifugoServer_BatchPublish_Call) Run(run func(ctx context.Context, channels []string, msg any)) *CentrifugoServer_BatchPublish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CentrifugoServer_BatchPublish_Call) Return(err error) *CentrifugoServer_BatchPublish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CentrifugoServer_BatchPublish_Call) RunAndReturn(run func(ctx context.Context, channels []string, msg any) error) *CentrifugoServer_BatchPublish_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type CentrifugoServer
func (_mock *CentrifugoServer) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CentrifugoServer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type CentrifugoServer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CentrifugoServer_Expecter) Close(ctx interface{}) *CentrifugoServer_Close_Call {
	return &CentrifugoServer_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *CentrifugoServer_Close_Call) Run(run func(ctx context.Context)) *CentrifugoServer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CentrifugoServer_Close_Call) Return(err error) *CentrifugoServer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CentrifugoServer_Close_Call) RunAndReturn(run func(ctx context.Context) error) *CentrifugoServer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type CentrifugoServer
func (_mock *CentrifugoServer) Connect(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CentrifugoServer_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type CentrifugoServer_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CentrifugoServer_Expecter) Connect(ctx interface{}) *CentrifugoServer_Connect_Call {
	return &CentrifugoServer_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *CentrifugoServer_Connect_Call) Run(run func(ctx context.Context)) *CentrifugoServer_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CentrifugoServer_Connect_Call) Return(err error) *CentrifugoServer_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CentrifugoServer_Connect_Call) RunAndReturn(run func(ctx context.Context) error) *CentrifugoServer_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// DisconnectUser provides a mock function for the type CentrifugoServer
func (_mock *CentrifugoServer) DisconnectUser(ctx context.Context, userId string) error {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for DisconnectUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CentrifugoServer_DisconnectUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectUser'
type CentrifugoServer_DisconnectUser_Call struct {
	*mock.Call
}

// DisconnectUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *CentrifugoServer_Expecter) DisconnectUser(ctx interface{}, userId interface{}) *CentrifugoServer_DisconnectUser_Call {
	return &CentrifugoServer_DisconnectUser_Call{Call: _e.mock.On("DisconnectUser", ctx, userId)}
}

func (_c *CentrifugoServer_DisconnectUser_Call) Run(run func(ctx context.Context, userId string)) *CentrifugoServer_DisconnectUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CentrifugoServer_DisconnectUser_Call) Return(err error) *CentrifugoServer_DisconnectUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CentrifugoServer_DisconnectUser_Call) RunAndReturn(run func(ctx context.Context, userId string) error) *CentrifugoServer_DisconnectUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresence provides a mock function for the type CentrifugoServer
func (_mock *CentrifugoServer) GetPresence(ctx context.Context, channel string) (*apiproto.PresenceResult, error) {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetPresence")
	}

	var r0 *apiproto.PresenceResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*apiproto.PresenceResult, error)); ok {
		return returnFunc(ctx, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *apiproto.PresenceResult); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiproto.PresenceResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CentrifugoServer_GetPresence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresence'
type CentrifugoServer_GetPresence_Call struct {
	*mock.Call
}

// GetPresence is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
func (_e *CentrifugoServer_Expecter) GetPresence(ctx interface{}, channel interface{}) *CentrifugoServer_GetPresence_Call {
	return &CentrifugoServer_GetPresence_Call{Call: _e.mock.On("GetPresence", ctx, channel)}
}

func (_c *CentrifugoServer_GetPresence_Call) Run(run func(ctx context.Context, channel string)) *CentrifugoServer_GetPresence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CentrifugoServer_GetPresence_Call) Return(presenceResult *apiproto.PresenceResult, err error) *CentrifugoServer_GetPresence_Call {
	_c.Call.Return(presenceResult, err)
	return _c
}

func (_c *CentrifugoServer_GetPresence_Call) RunAndReturn(run func(ctx context.Context, channel string) (*apiproto.PresenceResult, error)) *CentrifugoServer_GetPresence_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type CentrifugoServer
func (_mock *CentrifugoServer) Publish(ctx context.Context, channel string, msg any) error {
	ret := _mock.Called(ctx, channel, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, channel, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CentrifugoServer_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type CentrifugoServer_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
//   - msg any
func (_e *CentrifugoServer_Expecter) Publish(ctx interface{}, channel interface{}, msg interface{}) *CentrifugoServer_Publish_Call {
	return &CentrifugoServer_Publish_Call{Call: _e.mock.On("Publish", ctx, channel, msg)}
}

func (_c *CentrifugoServer_Publish_Call) Run(run func(ctx context.Context, channel string, msg any)) *CentrifugoServer_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CentrifugoServer_Publish_Call) Return(err error) *CentrifugoServer_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CentrifugoServer_Publish_Call) RunAndReturn(run func(ctx context.Context, channel string, msg any) error) *CentrifugoServer_Publish_Call {
	_c.Call.Return(run)
	return _c
}
