// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewClusterDistributedKeys creates a new instance of ClusterDistributedKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterDistributedKeys(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterDistributedKeys {
	mock := &ClusterDistributedKeys{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClusterDistributedKeys is an autogenerated mock type for the DistributedKeys type
type ClusterDistributedKeys struct {
	mock.Mock
}

type ClusterDistributedKeys_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterDistributedKeys) EXPECT() *ClusterDistributedKeys_Expecter {
	return &ClusterDistributedKeys_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type ClusterDistributedKeys
func (_mock *ClusterDistributedKeys) Check(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ClusterDistributedKeys_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type ClusterDistributedKeys_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - key string
func (_e *ClusterDistributedKeys_Expecter) Check(key interface{}) *ClusterDistributedKeys_Check_Call {
	return &ClusterDistributedKeys_Check_Call{Call: _e.mock.On("Check", key)}
}

func (_c *ClusterDistributedKeys_Check_Call) Run(run func(key string)) *ClusterDistributedKeys_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClusterDistributedKeys_Check_Call) Return(b bool) *ClusterDistributedKeys_Check_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ClusterDistributedKeys_Check_Call) RunAndReturn(run func(key string) bool) *ClusterDistributedKeys_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type ClusterDistributedKeys
func (_mock *ClusterDistributedKeys) Remove(key string) {
	_mock.Called(key)
	return
}

// ClusterDistributedKeys_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type ClusterDistributedKeys_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - key string
func (_e *ClusterDistributedKeys_Expecter) Remove(key interface{}) *ClusterDistributedKeys_Remove_Call {
	return &ClusterDistributedKeys_Remove_Call{Call: _e.mock.On("Remove", key)}
}

func (_c *ClusterDistributedKeys_Remove_Call) Run(run func(key string)) *ClusterDistributedKeys_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClusterDistributedKeys_Remove_Call) Return() *ClusterDistributedKeys_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClusterDistributedKeys_Remove_Call) RunAndReturn(run func(key string)) *ClusterDistributedKeys_Remove_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type ClusterDistributedKeys
func (_mock *ClusterDistributedKeys) Set(key string) {
	_mock.Called(key)
	return
}

// ClusterDistributedKeys_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type ClusterDistributedKeys_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
func (_e *ClusterDistributedKeys_Expecter) Set(key interface{}) *ClusterDistributedKeys_Set_Call {
	return &ClusterDistributedKeys_Set_Call{Call: _e.mock.On("Set", key)}
}

func (_c *ClusterDistributedKeys_Set_Call) Run(run func(key string)) *ClusterDistributedKeys_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClusterDistributedKeys_Set_Call) Return() *ClusterDistributedKeys_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClusterDistributedKeys_Set_Call) RunAndReturn(run func(key string)) *ClusterDistributedKeys_Set_Call {
	_c.Run(run)
	return _c
}

// NewClusterBootstrap creates a new instance of ClusterBootstrap. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterBootstrap(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterBootstrap {
	mock := &ClusterBootstrap{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClusterBootstrap is an autogenerated mock type for the Bootstrap type
type ClusterBootstrap struct {
	mock.Mock
}

type ClusterBootstrap_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterBootstrap) EXPECT() *ClusterBootstrap_Expecter {
	return &ClusterBootstrap_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ClusterBootstrap
func (_mock *ClusterBootstrap) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// ClusterBootstrap_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ClusterBootstrap_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ClusterBootstrap_Expecter) Close(ctx interface{}) *ClusterBootstrap_Close_Call {
	return &ClusterBootstrap_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *ClusterBootstrap_Close_Call) Run(run func(ctx context.Context)) *ClusterBootstrap_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClusterBootstrap_Close_Call) Return() *ClusterBootstrap_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClusterBootstrap_Close_Call) RunAndReturn(run func(ctx context.Context)) *ClusterBootstrap_Close_Call {
	_c.Run(run)
	return _c
}

// Init provides a mock function for the type ClusterBootstrap
func (_mock *ClusterBootstrap) Init(ctx context.Context, cfg any) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClusterBootstrap_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type ClusterBootstrap_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg any
func (_e *ClusterBootstrap_Expecter) Init(ctx interface{}, cfg interface{}) *ClusterBootstrap_Init_Call {
	return &ClusterBootstrap_Init_Call{Call: _e.mock.On("Init", ctx, cfg)}
}

func (_c *ClusterBootstrap_Init_Call) Run(run func(ctx context.Context, cfg any)) *ClusterBootstrap_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterBootstrap_Init_Call) Return(err error) *ClusterBootstrap_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClusterBootstrap_Init_Call) RunAndReturn(run func(ctx context.Context, cfg any) error) *ClusterBootstrap_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type ClusterBootstrap
func (_mock *ClusterBootstrap) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClusterBootstrap_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ClusterBootstrap_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ClusterBootstrap_Expecter) Start(ctx interface{}) *ClusterBootstrap_Start_Call {
	return &ClusterBootstrap_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *ClusterBootstrap_Start_Call) Run(run func(ctx context.Context)) *ClusterBootstrap_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClusterBootstrap_Start_Call) Return(err error) *ClusterBootstrap_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClusterBootstrap_Start_Call) RunAndReturn(run func(ctx context.Context) error) *ClusterBootstrap_Start_Call {
	_c.Call.Return(run)
	return _c
}
