// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewClusterBootstrap creates a new instance of ClusterBootstrap. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterBootstrap(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterBootstrap {
	mock := &ClusterBootstrap{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClusterBootstrap is an autogenerated mock type for the Bootstrap type
type ClusterBootstrap struct {
	mock.Mock
}

type ClusterBootstrap_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterBootstrap) EXPECT() *ClusterBootstrap_Expecter {
	return &ClusterBootstrap_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ClusterBootstrap
func (_mock *ClusterBootstrap) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// ClusterBootstrap_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ClusterBootstrap_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx
func (_e *ClusterBootstrap_Expecter) Close(ctx interface{}) *ClusterBootstrap_Close_Call {
	return &ClusterBootstrap_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *ClusterBootstrap_Close_Call) Run(run func(ctx context.Context)) *ClusterBootstrap_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ClusterBootstrap_Close_Call) Return() *ClusterBootstrap_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClusterBootstrap_Close_Call) RunAndReturn(run func(ctx context.Context)) *ClusterBootstrap_Close_Call {
	_c.Run(run)
	return _c
}

// Init provides a mock function for the type ClusterBootstrap
func (_mock *ClusterBootstrap) Init(ctx context.Context, cfg any) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClusterBootstrap_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type ClusterBootstrap_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx
//   - cfg
func (_e *ClusterBootstrap_Expecter) Init(ctx interface{}, cfg interface{}) *ClusterBootstrap_Init_Call {
	return &ClusterBootstrap_Init_Call{Call: _e.mock.On("Init", ctx, cfg)}
}

func (_c *ClusterBootstrap_Init_Call) Run(run func(ctx context.Context, cfg any)) *ClusterBootstrap_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(any))
	})
	return _c
}

func (_c *ClusterBootstrap_Init_Call) Return(err error) *ClusterBootstrap_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClusterBootstrap_Init_Call) RunAndReturn(run func(ctx context.Context, cfg any) error) *ClusterBootstrap_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type ClusterBootstrap
func (_mock *ClusterBootstrap) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClusterBootstrap_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ClusterBootstrap_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx
func (_e *ClusterBootstrap_Expecter) Start(ctx interface{}) *ClusterBootstrap_Start_Call {
	return &ClusterBootstrap_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *ClusterBootstrap_Start_Call) Run(run func(ctx context.Context)) *ClusterBootstrap_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ClusterBootstrap_Start_Call) Return(err error) *ClusterBootstrap_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClusterBootstrap_Start_Call) RunAndReturn(run func(ctx context.Context) error) *ClusterBootstrap_Start_Call {
	_c.Call.Return(run)
	return _c
}
