// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"
	"github.com/zloevil/jet/elasticsearch"
)

// NewElasticsearchSearch creates a new instance of ElasticsearchSearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElasticsearchSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElasticsearchSearch {
	mock := &ElasticsearchSearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ElasticsearchSearch is an autogenerated mock type for the Search type
type ElasticsearchSearch struct {
	mock.Mock
}

type ElasticsearchSearch_Expecter struct {
	mock *mock.Mock
}

func (_m *ElasticsearchSearch) EXPECT() *ElasticsearchSearch_Expecter {
	return &ElasticsearchSearch_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// ElasticsearchSearch_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ElasticsearchSearch_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ElasticsearchSearch_Expecter) Close(ctx interface{}) *ElasticsearchSearch_Close_Call {
	return &ElasticsearchSearch_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *ElasticsearchSearch_Close_Call) Run(run func(ctx context.Context)) *ElasticsearchSearch_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_Close_Call) Return() *ElasticsearchSearch_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *ElasticsearchSearch_Close_Call) RunAndReturn(run func(ctx context.Context)) *ElasticsearchSearch_Close_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) Delete(ctx context.Context, index string, id string) error {
	ret := _mock.Called(ctx, index, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, index, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElasticsearchSearch_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ElasticsearchSearch_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - id string
func (_e *ElasticsearchSearch_Expecter) Delete(ctx interface{}, index interface{}, id interface{}) *ElasticsearchSearch_Delete_Call {
	return &ElasticsearchSearch_Delete_Call{Call: _e.mock.On("Delete", ctx, index, id)}
}

func (_c *ElasticsearchSearch_Delete_Call) Run(run func(ctx context.Context, index string, id string)) *ElasticsearchSearch_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_Delete_Call) Return(err error) *ElasticsearchSearch_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElasticsearchSearch_Delete_Call) RunAndReturn(run func(ctx context.Context, index string, id string) error) *ElasticsearchSearch_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulk provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) DeleteBulk(ctx context.Context, index string, ids []string) error {
	ret := _mock.Called(ctx, index, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, index, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElasticsearchSearch_DeleteBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulk'
type ElasticsearchSearch_DeleteBulk_Call struct {
	*mock.Call
}

// DeleteBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - ids []string
func (_e *ElasticsearchSearch_Expecter) DeleteBulk(ctx interface{}, index interface{}, ids interface{}) *ElasticsearchSearch_DeleteBulk_Call {
	return &ElasticsearchSearch_DeleteBulk_Call{Call: _e.mock.On("DeleteBulk", ctx, index, ids)}
}

func (_c *ElasticsearchSearch_DeleteBulk_Call) Run(run func(ctx context.Context, index string, ids []string)) *ElasticsearchSearch_DeleteBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_DeleteBulk_Call) Return(err error) *ElasticsearchSearch_DeleteBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElasticsearchSearch_DeleteBulk_Call) RunAndReturn(run func(ctx context.Context, index string, ids []string) error) *ElasticsearchSearch_DeleteBulk_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIndex provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) DeleteIndex(ctx context.Context, index string) error {
	ret := _mock.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElasticsearchSearch_DeleteIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIndex'
type ElasticsearchSearch_DeleteIndex_Call struct {
	*mock.Call
}

// DeleteIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
func (_e *ElasticsearchSearch_Expecter) DeleteIndex(ctx interface{}, index interface{}) *ElasticsearchSearch_DeleteIndex_Call {
	return &ElasticsearchSearch_DeleteIndex_Call{Call: _e.mock.On("DeleteIndex", ctx, index)}
}

func (_c *ElasticsearchSearch_DeleteIndex_Call) Run(run func(ctx context.Context, index string)) *ElasticsearchSearch_DeleteIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_DeleteIndex_Call) Return(err error) *ElasticsearchSearch_DeleteIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElasticsearchSearch_DeleteIndex_Call) RunAndReturn(run func(ctx context.Context, index string) error) *ElasticsearchSearch_DeleteIndex_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) Exists(ctx context.Context, index string, id string) (bool, error) {
	ret := _mock.Called(ctx, index, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, index, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, index, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, index, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ElasticsearchSearch_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type ElasticsearchSearch_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - id string
func (_e *ElasticsearchSearch_Expecter) Exists(ctx interface{}, index interface{}, id interface{}) *ElasticsearchSearch_Exists_Call {
	return &ElasticsearchSearch_Exists_Call{Call: _e.mock.On("Exists", ctx, index, id)}
}

func (_c *ElasticsearchSearch_Exists_Call) Run(run func(ctx context.Context, index string, id string)) *ElasticsearchSearch_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_Exists_Call) Return(b bool, err error) *ElasticsearchSearch_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ElasticsearchSearch_Exists_Call) RunAndReturn(run func(ctx context.Context, index string, id string) (bool, error)) *ElasticsearchSearch_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) GetClient() *elastic.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *elastic.Client
	if returnFunc, ok := ret.Get(0).(func() *elastic.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Client)
		}
	}
	return r0
}

// ElasticsearchSearch_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type ElasticsearchSearch_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *ElasticsearchSearch_Expecter) GetClient() *ElasticsearchSearch_GetClient_Call {
	return &ElasticsearchSearch_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *ElasticsearchSearch_GetClient_Call) Run(run func()) *ElasticsearchSearch_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ElasticsearchSearch_GetClient_Call) Return(client *elastic.Client) *ElasticsearchSearch_GetClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *ElasticsearchSearch_GetClient_Call) RunAndReturn(run func() *elastic.Client) *ElasticsearchSearch_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) Index(ctx context.Context, index string, id string, data interface{}) error {
	ret := _mock.Called(ctx, index, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = returnFunc(ctx, index, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElasticsearchSearch_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type ElasticsearchSearch_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - id string
//   - data interface{}
func (_e *ElasticsearchSearch_Expecter) Index(ctx interface{}, index interface{}, id interface{}, data interface{}) *ElasticsearchSearch_Index_Call {
	return &ElasticsearchSearch_Index_Call{Call: _e.mock.On("Index", ctx, index, id, data)}
}

func (_c *ElasticsearchSearch_Index_Call) Run(run func(ctx context.Context, index string, id string, data interface{})) *ElasticsearchSearch_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_Index_Call) Return(err error) *ElasticsearchSearch_Index_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElasticsearchSearch_Index_Call) RunAndReturn(run func(ctx context.Context, index string, id string, data interface{}) error) *ElasticsearchSearch_Index_Call {
	_c.Call.Return(run)
	return _c
}

// IndexAsync provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) IndexAsync(ctx context.Context, index string, id string, data interface{}) {
	_mock.Called(ctx, index, id, data)
	return
}

// ElasticsearchSearch_IndexAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexAsync'
type ElasticsearchSearch_IndexAsync_Call struct {
	*mock.Call
}

// IndexAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - id string
//   - data interface{}
func (_e *ElasticsearchSearch_Expecter) IndexAsync(ctx interface{}, index interface{}, id interface{}, data interface{}) *ElasticsearchSearch_IndexAsync_Call {
	return &ElasticsearchSearch_IndexAsync_Call{Call: _e.mock.On("IndexAsync", ctx, index, id, data)}
}

func (_c *ElasticsearchSearch_IndexAsync_Call) Run(run func(ctx context.Context, index string, id string, data interface{})) *ElasticsearchSearch_IndexAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_IndexAsync_Call) Return() *ElasticsearchSearch_IndexAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *ElasticsearchSearch_IndexAsync_Call) RunAndReturn(run func(ctx context.Context, index string, id string, data interface{})) *ElasticsearchSearch_IndexAsync_Call {
	_c.Run(run)
	return _c
}

// IndexBulk provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) IndexBulk(ctx context.Context, index string, docs map[string]interface{}) error {
	ret := _mock.Called(ctx, index, docs)

	if len(ret) == 0 {
		panic("no return value specified for IndexBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, index, docs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElasticsearchSearch_IndexBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexBulk'
type ElasticsearchSearch_IndexBulk_Call struct {
	*mock.Call
}

// IndexBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - docs map[string]interface{}
func (_e *ElasticsearchSearch_Expecter) IndexBulk(ctx interface{}, index interface{}, docs interface{}) *ElasticsearchSearch_IndexBulk_Call {
	return &ElasticsearchSearch_IndexBulk_Call{Call: _e.mock.On("IndexBulk", ctx, index, docs)}
}

func (_c *ElasticsearchSearch_IndexBulk_Call) Run(run func(ctx context.Context, index string, docs map[string]interface{})) *ElasticsearchSearch_IndexBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_IndexBulk_Call) Return(err error) *ElasticsearchSearch_IndexBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElasticsearchSearch_IndexBulk_Call) RunAndReturn(run func(ctx context.Context, index string, docs map[string]interface{}) error) *ElasticsearchSearch_IndexBulk_Call {
	_c.Call.Return(run)
	return _c
}

// IndexBulkAsync provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) IndexBulkAsync(ctx context.Context, index string, docs map[string]interface{}) {
	_mock.Called(ctx, index, docs)
	return
}

// ElasticsearchSearch_IndexBulkAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexBulkAsync'
type ElasticsearchSearch_IndexBulkAsync_Call struct {
	*mock.Call
}

// IndexBulkAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - docs map[string]interface{}
func (_e *ElasticsearchSearch_Expecter) IndexBulkAsync(ctx interface{}, index interface{}, docs interface{}) *ElasticsearchSearch_IndexBulkAsync_Call {
	return &ElasticsearchSearch_IndexBulkAsync_Call{Call: _e.mock.On("IndexBulkAsync", ctx, index, docs)}
}

func (_c *ElasticsearchSearch_IndexBulkAsync_Call) Run(run func(ctx context.Context, index string, docs map[string]interface{})) *ElasticsearchSearch_IndexBulkAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_IndexBulkAsync_Call) Return() *ElasticsearchSearch_IndexBulkAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *ElasticsearchSearch_IndexBulkAsync_Call) RunAndReturn(run func(ctx context.Context, index string, docs map[string]interface{})) *ElasticsearchSearch_IndexBulkAsync_Call {
	_c.Run(run)
	return _c
}

// NewBuilder provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) NewBuilder() elasticsearch.IndexBuilder {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewBuilder")
	}

	var r0 elasticsearch.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func() elasticsearch.IndexBuilder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elasticsearch.IndexBuilder)
		}
	}
	return r0
}

// ElasticsearchSearch_NewBuilder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewBuilder'
type ElasticsearchSearch_NewBuilder_Call struct {
	*mock.Call
}

// NewBuilder is a helper method to define mock.On call
func (_e *ElasticsearchSearch_Expecter) NewBuilder() *ElasticsearchSearch_NewBuilder_Call {
	return &ElasticsearchSearch_NewBuilder_Call{Call: _e.mock.On("NewBuilder")}
}

func (_c *ElasticsearchSearch_NewBuilder_Call) Run(run func()) *ElasticsearchSearch_NewBuilder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ElasticsearchSearch_NewBuilder_Call) Return(indexBuilder elasticsearch.IndexBuilder) *ElasticsearchSearch_NewBuilder_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *ElasticsearchSearch_NewBuilder_Call) RunAndReturn(run func() elasticsearch.IndexBuilder) *ElasticsearchSearch_NewBuilder_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) Ping() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ElasticsearchSearch_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type ElasticsearchSearch_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *ElasticsearchSearch_Expecter) Ping() *ElasticsearchSearch_Ping_Call {
	return &ElasticsearchSearch_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *ElasticsearchSearch_Ping_Call) Run(run func()) *ElasticsearchSearch_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ElasticsearchSearch_Ping_Call) Return(b bool) *ElasticsearchSearch_Ping_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ElasticsearchSearch_Ping_Call) RunAndReturn(run func() bool) *ElasticsearchSearch_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type ElasticsearchSearch
func (_mock *ElasticsearchSearch) Refresh(ctx context.Context, index string) error {
	ret := _mock.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElasticsearchSearch_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type ElasticsearchSearch_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
func (_e *ElasticsearchSearch_Expecter) Refresh(ctx interface{}, index interface{}) *ElasticsearchSearch_Refresh_Call {
	return &ElasticsearchSearch_Refresh_Call{Call: _e.mock.On("Refresh", ctx, index)}
}

func (_c *ElasticsearchSearch_Refresh_Call) Run(run func(ctx context.Context, index string)) *ElasticsearchSearch_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ElasticsearchSearch_Refresh_Call) Return(err error) *ElasticsearchSearch_Refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElasticsearchSearch_Refresh_Call) RunAndReturn(run func(ctx context.Context, index string) error) *ElasticsearchSearch_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewElasticsearchIndexBuilder creates a new instance of ElasticsearchIndexBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElasticsearchIndexBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElasticsearchIndexBuilder {
	mock := &ElasticsearchIndexBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ElasticsearchIndexBuilder is an autogenerated mock type for the IndexBuilder type
type ElasticsearchIndexBuilder struct {
	mock.Mock
}

type ElasticsearchIndexBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *ElasticsearchIndexBuilder) EXPECT() *ElasticsearchIndexBuilder_Expecter {
	return &ElasticsearchIndexBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type ElasticsearchIndexBuilder
func (_mock *ElasticsearchIndexBuilder) Build(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElasticsearchIndexBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type ElasticsearchIndexBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ElasticsearchIndexBuilder_Expecter) Build(ctx interface{}) *ElasticsearchIndexBuilder_Build_Call {
	return &ElasticsearchIndexBuilder_Build_Call{Call: _e.mock.On("Build", ctx)}
}

func (_c *ElasticsearchIndexBuilder_Build_Call) Run(run func(ctx context.Context)) *ElasticsearchIndexBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ElasticsearchIndexBuilder_Build_Call) Return(err error) *ElasticsearchIndexBuilder_Build_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElasticsearchIndexBuilder_Build_Call) RunAndReturn(run func(ctx context.Context) error) *ElasticsearchIndexBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// WithAlias provides a mock function for the type ElasticsearchIndexBuilder
func (_mock *ElasticsearchIndexBuilder) WithAlias(name string) elasticsearch.IndexBuilder {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithAlias")
	}

	var r0 elasticsearch.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(string) elasticsearch.IndexBuilder); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elasticsearch.IndexBuilder)
		}
	}
	return r0
}

// ElasticsearchIndexBuilder_WithAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithAlias'
type ElasticsearchIndexBuilder_WithAlias_Call struct {
	*mock.Call
}

// WithAlias is a helper method to define mock.On call
//   - name string
func (_e *ElasticsearchIndexBuilder_Expecter) WithAlias(name interface{}) *ElasticsearchIndexBuilder_WithAlias_Call {
	return &ElasticsearchIndexBuilder_WithAlias_Call{Call: _e.mock.On("WithAlias", name)}
}

func (_c *ElasticsearchIndexBuilder_WithAlias_Call) Run(run func(name string)) *ElasticsearchIndexBuilder_WithAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ElasticsearchIndexBuilder_WithAlias_Call) Return(indexBuilder elasticsearch.IndexBuilder) *ElasticsearchIndexBuilder_WithAlias_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *ElasticsearchIndexBuilder_WithAlias_Call) RunAndReturn(run func(name string) elasticsearch.IndexBuilder) *ElasticsearchIndexBuilder_WithAlias_Call {
	_c.Call.Return(run)
	return _c
}

// WithExplicitMapping provides a mock function for the type ElasticsearchIndexBuilder
func (_mock *ElasticsearchIndexBuilder) WithExplicitMapping(mapping string) elasticsearch.IndexBuilder {
	ret := _mock.Called(mapping)

	if len(ret) == 0 {
		panic("no return value specified for WithExplicitMapping")
	}

	var r0 elasticsearch.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(string) elasticsearch.IndexBuilder); ok {
		r0 = returnFunc(mapping)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elasticsearch.IndexBuilder)
		}
	}
	return r0
}

// ElasticsearchIndexBuilder_WithExplicitMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithExplicitMapping'
type ElasticsearchIndexBuilder_WithExplicitMapping_Call struct {
	*mock.Call
}

// WithExplicitMapping is a helper method to define mock.On call
//   - mapping string
func (_e *ElasticsearchIndexBuilder_Expecter) WithExplicitMapping(mapping interface{}) *ElasticsearchIndexBuilder_WithExplicitMapping_Call {
	return &ElasticsearchIndexBuilder_WithExplicitMapping_Call{Call: _e.mock.On("WithExplicitMapping", mapping)}
}

func (_c *ElasticsearchIndexBuilder_WithExplicitMapping_Call) Run(run func(mapping string)) *ElasticsearchIndexBuilder_WithExplicitMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ElasticsearchIndexBuilder_WithExplicitMapping_Call) Return(indexBuilder elasticsearch.IndexBuilder) *ElasticsearchIndexBuilder_WithExplicitMapping_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *ElasticsearchIndexBuilder_WithExplicitMapping_Call) RunAndReturn(run func(mapping string) elasticsearch.IndexBuilder) *ElasticsearchIndexBuilder_WithExplicitMapping_Call {
	_c.Call.Return(run)
	return _c
}

// WithIndex provides a mock function for the type ElasticsearchIndexBuilder
func (_mock *ElasticsearchIndexBuilder) WithIndex(name string) elasticsearch.IndexBuilder {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithIndex")
	}

	var r0 elasticsearch.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(string) elasticsearch.IndexBuilder); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elasticsearch.IndexBuilder)
		}
	}
	return r0
}

// ElasticsearchIndexBuilder_WithIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithIndex'
type ElasticsearchIndexBuilder_WithIndex_Call struct {
	*mock.Call
}

// WithIndex is a helper method to define mock.On call
//   - name string
func (_e *ElasticsearchIndexBuilder_Expecter) WithIndex(name interface{}) *ElasticsearchIndexBuilder_WithIndex_Call {
	return &ElasticsearchIndexBuilder_WithIndex_Call{Call: _e.mock.On("WithIndex", name)}
}

func (_c *ElasticsearchIndexBuilder_WithIndex_Call) Run(run func(name string)) *ElasticsearchIndexBuilder_WithIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ElasticsearchIndexBuilder_WithIndex_Call) Return(indexBuilder elasticsearch.IndexBuilder) *ElasticsearchIndexBuilder_WithIndex_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *ElasticsearchIndexBuilder_WithIndex_Call) RunAndReturn(run func(name string) elasticsearch.IndexBuilder) *ElasticsearchIndexBuilder_WithIndex_Call {
	_c.Call.Return(run)
	return _c
}

// WithMappingModel provides a mock function for the type ElasticsearchIndexBuilder
func (_mock *ElasticsearchIndexBuilder) WithMappingModel(model interface{}) elasticsearch.IndexBuilder {
	ret := _mock.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for WithMappingModel")
	}

	var r0 elasticsearch.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(interface{}) elasticsearch.IndexBuilder); ok {
		r0 = returnFunc(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elasticsearch.IndexBuilder)
		}
	}
	return r0
}

// ElasticsearchIndexBuilder_WithMappingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithMappingModel'
type ElasticsearchIndexBuilder_WithMappingModel_Call struct {
	*mock.Call
}

// WithMappingModel is a helper method to define mock.On call
//   - model interface{}
func (_e *ElasticsearchIndexBuilder_Expecter) WithMappingModel(model interface{}) *ElasticsearchIndexBuilder_WithMappingModel_Call {
	return &ElasticsearchIndexBuilder_WithMappingModel_Call{Call: _e.mock.On("WithMappingModel", model)}
}

func (_c *ElasticsearchIndexBuilder_WithMappingModel_Call) Run(run func(model interface{})) *ElasticsearchIndexBuilder_WithMappingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ElasticsearchIndexBuilder_WithMappingModel_Call) Return(indexBuilder elasticsearch.IndexBuilder) *ElasticsearchIndexBuilder_WithMappingModel_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *ElasticsearchIndexBuilder_WithMappingModel_Call) RunAndReturn(run func(model interface{}) elasticsearch.IndexBuilder) *ElasticsearchIndexBuilder_WithMappingModel_Call {
	_c.Call.Return(run)
	return _c
}
