// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/zloevil/jet/google"
	"google.golang.org/api/oauth2/v2"
)

// NewGoogleCaptcha creates a new instance of GoogleCaptcha. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleCaptcha(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleCaptcha {
	mock := &GoogleCaptcha{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GoogleCaptcha is an autogenerated mock type for the Captcha type
type GoogleCaptcha struct {
	mock.Mock
}

type GoogleCaptcha_Expecter struct {
	mock *mock.Mock
}

func (_m *GoogleCaptcha) EXPECT() *GoogleCaptcha_Expecter {
	return &GoogleCaptcha_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type GoogleCaptcha
func (_mock *GoogleCaptcha) Verify(ctx context.Context, rq *google.CaptchaRequest) (bool, error) {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *google.CaptchaRequest) (bool, error)); ok {
		return returnFunc(ctx, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *google.CaptchaRequest) bool); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *google.CaptchaRequest) error); ok {
		r1 = returnFunc(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GoogleCaptcha_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type GoogleCaptcha_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx
//   - rq
func (_e *GoogleCaptcha_Expecter) Verify(ctx interface{}, rq interface{}) *GoogleCaptcha_Verify_Call {
	return &GoogleCaptcha_Verify_Call{Call: _e.mock.On("Verify", ctx, rq)}
}

func (_c *GoogleCaptcha_Verify_Call) Run(run func(ctx context.Context, rq *google.CaptchaRequest)) *GoogleCaptcha_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*google.CaptchaRequest))
	})
	return _c
}

func (_c *GoogleCaptcha_Verify_Call) Return(b bool, err error) *GoogleCaptcha_Verify_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *GoogleCaptcha_Verify_Call) RunAndReturn(run func(ctx context.Context, rq *google.CaptchaRequest) (bool, error)) *GoogleCaptcha_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewGoogleOAuth2 creates a new instance of GoogleOAuth2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleOAuth2(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleOAuth2 {
	mock := &GoogleOAuth2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GoogleOAuth2 is an autogenerated mock type for the OAuth2 type
type GoogleOAuth2 struct {
	mock.Mock
}

type GoogleOAuth2_Expecter struct {
	mock *mock.Mock
}

func (_m *GoogleOAuth2) EXPECT() *GoogleOAuth2_Expecter {
	return &GoogleOAuth2_Expecter{mock: &_m.Mock}
}

// GetGoogleUser provides a mock function for the type GoogleOAuth2
func (_mock *GoogleOAuth2) GetGoogleUser(ctx context.Context, token string) (*oauth2.Userinfo, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetGoogleUser")
	}

	var r0 *oauth2.Userinfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*oauth2.Userinfo, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *oauth2.Userinfo); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Userinfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GoogleOAuth2_GetGoogleUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGoogleUser'
type GoogleOAuth2_GetGoogleUser_Call struct {
	*mock.Call
}

// GetGoogleUser is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *GoogleOAuth2_Expecter) GetGoogleUser(ctx interface{}, token interface{}) *GoogleOAuth2_GetGoogleUser_Call {
	return &GoogleOAuth2_GetGoogleUser_Call{Call: _e.mock.On("GetGoogleUser", ctx, token)}
}

func (_c *GoogleOAuth2_GetGoogleUser_Call) Run(run func(ctx context.Context, token string)) *GoogleOAuth2_GetGoogleUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GoogleOAuth2_GetGoogleUser_Call) Return(userinfo *oauth2.Userinfo, err error) *GoogleOAuth2_GetGoogleUser_Call {
	_c.Call.Return(userinfo, err)
	return _c
}

func (_c *GoogleOAuth2_GetGoogleUser_Call) RunAndReturn(run func(ctx context.Context, token string) (*oauth2.Userinfo, error)) *GoogleOAuth2_GetGoogleUser_Call {
	_c.Call.Return(run)
	return _c
}
