// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/zloevil/jet"
	"github.com/zloevil/jet/goroutine"
)

// NewGoroutineErrGroup creates a new instance of GoroutineErrGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoroutineErrGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoroutineErrGroup {
	mock := &GoroutineErrGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GoroutineErrGroup is an autogenerated mock type for the ErrGroup type
type GoroutineErrGroup struct {
	mock.Mock
}

type GoroutineErrGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *GoroutineErrGroup) EXPECT() *GoroutineErrGroup_Expecter {
	return &GoroutineErrGroup_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type GoroutineErrGroup
func (_mock *GoroutineErrGroup) Cancel() {
	_mock.Called()
	return
}

// GoroutineErrGroup_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type GoroutineErrGroup_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
func (_e *GoroutineErrGroup_Expecter) Cancel() *GoroutineErrGroup_Cancel_Call {
	return &GoroutineErrGroup_Cancel_Call{Call: _e.mock.On("Cancel")}
}

func (_c *GoroutineErrGroup_Cancel_Call) Run(run func()) *GoroutineErrGroup_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GoroutineErrGroup_Cancel_Call) Return() *GoroutineErrGroup_Cancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *GoroutineErrGroup_Cancel_Call) RunAndReturn(run func()) *GoroutineErrGroup_Cancel_Call {
	_c.Run(run)
	return _c
}

// CancelFunc provides a mock function for the type GoroutineErrGroup
func (_mock *GoroutineErrGroup) CancelFunc() func() {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CancelFunc")
	}

	var r0 func()
	if returnFunc, ok := ret.Get(0).(func() func()); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}
	return r0
}

// GoroutineErrGroup_CancelFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelFunc'
type GoroutineErrGroup_CancelFunc_Call struct {
	*mock.Call
}

// CancelFunc is a helper method to define mock.On call
func (_e *GoroutineErrGroup_Expecter) CancelFunc() *GoroutineErrGroup_CancelFunc_Call {
	return &GoroutineErrGroup_CancelFunc_Call{Call: _e.mock.On("CancelFunc")}
}

func (_c *GoroutineErrGroup_CancelFunc_Call) Run(run func()) *GoroutineErrGroup_CancelFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GoroutineErrGroup_CancelFunc_Call) Return(fn func()) *GoroutineErrGroup_CancelFunc_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *GoroutineErrGroup_CancelFunc_Call) RunAndReturn(run func() func()) *GoroutineErrGroup_CancelFunc_Call {
	_c.Call.Return(run)
	return _c
}

// Cmp provides a mock function for the type GoroutineErrGroup
func (_mock *GoroutineErrGroup) Cmp(component string) goroutine.ErrGroup {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for Cmp")
	}

	var r0 goroutine.ErrGroup
	if returnFunc, ok := ret.Get(0).(func(string) goroutine.ErrGroup); ok {
		r0 = returnFunc(component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.ErrGroup)
		}
	}
	return r0
}

// GoroutineErrGroup_Cmp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cmp'
type GoroutineErrGroup_Cmp_Call struct {
	*mock.Call
}

// Cmp is a helper method to define mock.On call
//   - component string
func (_e *GoroutineErrGroup_Expecter) Cmp(component interface{}) *GoroutineErrGroup_Cmp_Call {
	return &GoroutineErrGroup_Cmp_Call{Call: _e.mock.On("Cmp", component)}
}

func (_c *GoroutineErrGroup_Cmp_Call) Run(run func(component string)) *GoroutineErrGroup_Cmp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineErrGroup_Cmp_Call) Return(errGroup goroutine.ErrGroup) *GoroutineErrGroup_Cmp_Call {
	_c.Call.Return(errGroup)
	return _c
}

func (_c *GoroutineErrGroup_Cmp_Call) RunAndReturn(run func(component string) goroutine.ErrGroup) *GoroutineErrGroup_Cmp_Call {
	_c.Call.Return(run)
	return _c
}

// Go provides a mock function for the type GoroutineErrGroup
func (_mock *GoroutineErrGroup) Go(f func() error) {
	_mock.Called(f)
	return
}

// GoroutineErrGroup_Go_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Go'
type GoroutineErrGroup_Go_Call struct {
	*mock.Call
}

// Go is a helper method to define mock.On call
//   - f func() error
func (_e *GoroutineErrGroup_Expecter) Go(f interface{}) *GoroutineErrGroup_Go_Call {
	return &GoroutineErrGroup_Go_Call{Call: _e.mock.On("Go", f)}
}

func (_c *GoroutineErrGroup_Go_Call) Run(run func(f func() error)) *GoroutineErrGroup_Go_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() error
		if args[0] != nil {
			arg0 = args[0].(func() error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineErrGroup_Go_Call) Return() *GoroutineErrGroup_Go_Call {
	_c.Call.Return()
	return _c
}

func (_c *GoroutineErrGroup_Go_Call) RunAndReturn(run func(f func() error)) *GoroutineErrGroup_Go_Call {
	_c.Run(run)
	return _c
}

// Mth provides a mock function for the type GoroutineErrGroup
func (_mock *GoroutineErrGroup) Mth(method string) goroutine.ErrGroup {
	ret := _mock.Called(method)

	if len(ret) == 0 {
		panic("no return value specified for Mth")
	}

	var r0 goroutine.ErrGroup
	if returnFunc, ok := ret.Get(0).(func(string) goroutine.ErrGroup); ok {
		r0 = returnFunc(method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.ErrGroup)
		}
	}
	return r0
}

// GoroutineErrGroup_Mth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mth'
type GoroutineErrGroup_Mth_Call struct {
	*mock.Call
}

// Mth is a helper method to define mock.On call
//   - method string
func (_e *GoroutineErrGroup_Expecter) Mth(method interface{}) *GoroutineErrGroup_Mth_Call {
	return &GoroutineErrGroup_Mth_Call{Call: _e.mock.On("Mth", method)}
}

func (_c *GoroutineErrGroup_Mth_Call) Run(run func(method string)) *GoroutineErrGroup_Mth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineErrGroup_Mth_Call) Return(errGroup goroutine.ErrGroup) *GoroutineErrGroup_Mth_Call {
	_c.Call.Return(errGroup)
	return _c
}

func (_c *GoroutineErrGroup_Mth_Call) RunAndReturn(run func(method string) goroutine.ErrGroup) *GoroutineErrGroup_Mth_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type GoroutineErrGroup
func (_mock *GoroutineErrGroup) Wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GoroutineErrGroup_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type GoroutineErrGroup_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *GoroutineErrGroup_Expecter) Wait() *GoroutineErrGroup_Wait_Call {
	return &GoroutineErrGroup_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *GoroutineErrGroup_Wait_Call) Run(run func()) *GoroutineErrGroup_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GoroutineErrGroup_Wait_Call) Return(err error) *GoroutineErrGroup_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GoroutineErrGroup_Wait_Call) RunAndReturn(run func() error) *GoroutineErrGroup_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// WithLogger provides a mock function for the type GoroutineErrGroup
func (_mock *GoroutineErrGroup) WithLogger(logger jet.CLogger) goroutine.ErrGroup {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for WithLogger")
	}

	var r0 goroutine.ErrGroup
	if returnFunc, ok := ret.Get(0).(func(jet.CLogger) goroutine.ErrGroup); ok {
		r0 = returnFunc(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.ErrGroup)
		}
	}
	return r0
}

// GoroutineErrGroup_WithLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLogger'
type GoroutineErrGroup_WithLogger_Call struct {
	*mock.Call
}

// WithLogger is a helper method to define mock.On call
//   - logger jet.CLogger
func (_e *GoroutineErrGroup_Expecter) WithLogger(logger interface{}) *GoroutineErrGroup_WithLogger_Call {
	return &GoroutineErrGroup_WithLogger_Call{Call: _e.mock.On("WithLogger", logger)}
}

func (_c *GoroutineErrGroup_WithLogger_Call) Run(run func(logger jet.CLogger)) *GoroutineErrGroup_WithLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jet.CLogger
		if args[0] != nil {
			arg0 = args[0].(jet.CLogger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineErrGroup_WithLogger_Call) Return(errGroup goroutine.ErrGroup) *GoroutineErrGroup_WithLogger_Call {
	_c.Call.Return(errGroup)
	return _c
}

func (_c *GoroutineErrGroup_WithLogger_Call) RunAndReturn(run func(logger jet.CLogger) goroutine.ErrGroup) *GoroutineErrGroup_WithLogger_Call {
	_c.Call.Return(run)
	return _c
}

// WithLoggerFn provides a mock function for the type GoroutineErrGroup
func (_mock *GoroutineErrGroup) WithLoggerFn(loggerFn jet.CLoggerFunc) goroutine.ErrGroup {
	ret := _mock.Called(loggerFn)

	if len(ret) == 0 {
		panic("no return value specified for WithLoggerFn")
	}

	var r0 goroutine.ErrGroup
	if returnFunc, ok := ret.Get(0).(func(jet.CLoggerFunc) goroutine.ErrGroup); ok {
		r0 = returnFunc(loggerFn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.ErrGroup)
		}
	}
	return r0
}

// GoroutineErrGroup_WithLoggerFn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLoggerFn'
type GoroutineErrGroup_WithLoggerFn_Call struct {
	*mock.Call
}

// WithLoggerFn is a helper method to define mock.On call
//   - loggerFn jet.CLoggerFunc
func (_e *GoroutineErrGroup_Expecter) WithLoggerFn(loggerFn interface{}) *GoroutineErrGroup_WithLoggerFn_Call {
	return &GoroutineErrGroup_WithLoggerFn_Call{Call: _e.mock.On("WithLoggerFn", loggerFn)}
}

func (_c *GoroutineErrGroup_WithLoggerFn_Call) Run(run func(loggerFn jet.CLoggerFunc)) *GoroutineErrGroup_WithLoggerFn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jet.CLoggerFunc
		if args[0] != nil {
			arg0 = args[0].(jet.CLoggerFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineErrGroup_WithLoggerFn_Call) Return(errGroup goroutine.ErrGroup) *GoroutineErrGroup_WithLoggerFn_Call {
	_c.Call.Return(errGroup)
	return _c
}

func (_c *GoroutineErrGroup_WithLoggerFn_Call) RunAndReturn(run func(loggerFn jet.CLoggerFunc) goroutine.ErrGroup) *GoroutineErrGroup_WithLoggerFn_Call {
	_c.Call.Return(run)
	return _c
}

// NewGoroutineGoroutine creates a new instance of GoroutineGoroutine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoroutineGoroutine(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoroutineGoroutine {
	mock := &GoroutineGoroutine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GoroutineGoroutine is an autogenerated mock type for the Goroutine type
type GoroutineGoroutine struct {
	mock.Mock
}

type GoroutineGoroutine_Expecter struct {
	mock *mock.Mock
}

func (_m *GoroutineGoroutine) EXPECT() *GoroutineGoroutine_Expecter {
	return &GoroutineGoroutine_Expecter{mock: &_m.Mock}
}

// Cmp provides a mock function for the type GoroutineGoroutine
func (_mock *GoroutineGoroutine) Cmp(component string) goroutine.Goroutine {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for Cmp")
	}

	var r0 goroutine.Goroutine
	if returnFunc, ok := ret.Get(0).(func(string) goroutine.Goroutine); ok {
		r0 = returnFunc(component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.Goroutine)
		}
	}
	return r0
}

// GoroutineGoroutine_Cmp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cmp'
type GoroutineGoroutine_Cmp_Call struct {
	*mock.Call
}

// Cmp is a helper method to define mock.On call
//   - component string
func (_e *GoroutineGoroutine_Expecter) Cmp(component interface{}) *GoroutineGoroutine_Cmp_Call {
	return &GoroutineGoroutine_Cmp_Call{Call: _e.mock.On("Cmp", component)}
}

func (_c *GoroutineGoroutine_Cmp_Call) Run(run func(component string)) *GoroutineGoroutine_Cmp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineGoroutine_Cmp_Call) Return(goroutine1 goroutine.Goroutine) *GoroutineGoroutine_Cmp_Call {
	_c.Call.Return(goroutine1)
	return _c
}

func (_c *GoroutineGoroutine_Cmp_Call) RunAndReturn(run func(component string) goroutine.Goroutine) *GoroutineGoroutine_Cmp_Call {
	_c.Call.Return(run)
	return _c
}

// Go provides a mock function for the type GoroutineGoroutine
func (_mock *GoroutineGoroutine) Go(ctx context.Context, f func()) {
	_mock.Called(ctx, f)
	return
}

// GoroutineGoroutine_Go_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Go'
type GoroutineGoroutine_Go_Call struct {
	*mock.Call
}

// Go is a helper method to define mock.On call
//   - ctx context.Context
//   - f func()
func (_e *GoroutineGoroutine_Expecter) Go(ctx interface{}, f interface{}) *GoroutineGoroutine_Go_Call {
	return &GoroutineGoroutine_Go_Call{Call: _e.mock.On("Go", ctx, f)}
}

func (_c *GoroutineGoroutine_Go_Call) Run(run func(ctx context.Context, f func())) *GoroutineGoroutine_Go_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func()
		if args[1] != nil {
			arg1 = args[1].(func())
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GoroutineGoroutine_Go_Call) Return() *GoroutineGoroutine_Go_Call {
	_c.Call.Return()
	return _c
}

func (_c *GoroutineGoroutine_Go_Call) RunAndReturn(run func(ctx context.Context, f func())) *GoroutineGoroutine_Go_Call {
	_c.Run(run)
	return _c
}

// Mth provides a mock function for the type GoroutineGoroutine
func (_mock *GoroutineGoroutine) Mth(method string) goroutine.Goroutine {
	ret := _mock.Called(method)

	if len(ret) == 0 {
		panic("no return value specified for Mth")
	}

	var r0 goroutine.Goroutine
	if returnFunc, ok := ret.Get(0).(func(string) goroutine.Goroutine); ok {
		r0 = returnFunc(method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.Goroutine)
		}
	}
	return r0
}

// GoroutineGoroutine_Mth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mth'
type GoroutineGoroutine_Mth_Call struct {
	*mock.Call
}

// Mth is a helper method to define mock.On call
//   - method string
func (_e *GoroutineGoroutine_Expecter) Mth(method interface{}) *GoroutineGoroutine_Mth_Call {
	return &GoroutineGoroutine_Mth_Call{Call: _e.mock.On("Mth", method)}
}

func (_c *GoroutineGoroutine_Mth_Call) Run(run func(method string)) *GoroutineGoroutine_Mth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineGoroutine_Mth_Call) Return(goroutine1 goroutine.Goroutine) *GoroutineGoroutine_Mth_Call {
	_c.Call.Return(goroutine1)
	return _c
}

func (_c *GoroutineGoroutine_Mth_Call) RunAndReturn(run func(method string) goroutine.Goroutine) *GoroutineGoroutine_Mth_Call {
	_c.Call.Return(run)
	return _c
}

// WithLogger provides a mock function for the type GoroutineGoroutine
func (_mock *GoroutineGoroutine) WithLogger(logger jet.CLogger) goroutine.Goroutine {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for WithLogger")
	}

	var r0 goroutine.Goroutine
	if returnFunc, ok := ret.Get(0).(func(jet.CLogger) goroutine.Goroutine); ok {
		r0 = returnFunc(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.Goroutine)
		}
	}
	return r0
}

// GoroutineGoroutine_WithLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLogger'
type GoroutineGoroutine_WithLogger_Call struct {
	*mock.Call
}

// WithLogger is a helper method to define mock.On call
//   - logger jet.CLogger
func (_e *GoroutineGoroutine_Expecter) WithLogger(logger interface{}) *GoroutineGoroutine_WithLogger_Call {
	return &GoroutineGoroutine_WithLogger_Call{Call: _e.mock.On("WithLogger", logger)}
}

func (_c *GoroutineGoroutine_WithLogger_Call) Run(run func(logger jet.CLogger)) *GoroutineGoroutine_WithLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jet.CLogger
		if args[0] != nil {
			arg0 = args[0].(jet.CLogger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineGoroutine_WithLogger_Call) Return(goroutine1 goroutine.Goroutine) *GoroutineGoroutine_WithLogger_Call {
	_c.Call.Return(goroutine1)
	return _c
}

func (_c *GoroutineGoroutine_WithLogger_Call) RunAndReturn(run func(logger jet.CLogger) goroutine.Goroutine) *GoroutineGoroutine_WithLogger_Call {
	_c.Call.Return(run)
	return _c
}

// WithLoggerFn provides a mock function for the type GoroutineGoroutine
func (_mock *GoroutineGoroutine) WithLoggerFn(loggerFn jet.CLoggerFunc) goroutine.Goroutine {
	ret := _mock.Called(loggerFn)

	if len(ret) == 0 {
		panic("no return value specified for WithLoggerFn")
	}

	var r0 goroutine.Goroutine
	if returnFunc, ok := ret.Get(0).(func(jet.CLoggerFunc) goroutine.Goroutine); ok {
		r0 = returnFunc(loggerFn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.Goroutine)
		}
	}
	return r0
}

// GoroutineGoroutine_WithLoggerFn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLoggerFn'
type GoroutineGoroutine_WithLoggerFn_Call struct {
	*mock.Call
}

// WithLoggerFn is a helper method to define mock.On call
//   - loggerFn jet.CLoggerFunc
func (_e *GoroutineGoroutine_Expecter) WithLoggerFn(loggerFn interface{}) *GoroutineGoroutine_WithLoggerFn_Call {
	return &GoroutineGoroutine_WithLoggerFn_Call{Call: _e.mock.On("WithLoggerFn", loggerFn)}
}

func (_c *GoroutineGoroutine_WithLoggerFn_Call) Run(run func(loggerFn jet.CLoggerFunc)) *GoroutineGoroutine_WithLoggerFn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jet.CLoggerFunc
		if args[0] != nil {
			arg0 = args[0].(jet.CLoggerFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineGoroutine_WithLoggerFn_Call) Return(goroutine1 goroutine.Goroutine) *GoroutineGoroutine_WithLoggerFn_Call {
	_c.Call.Return(goroutine1)
	return _c
}

func (_c *GoroutineGoroutine_WithLoggerFn_Call) RunAndReturn(run func(loggerFn jet.CLoggerFunc) goroutine.Goroutine) *GoroutineGoroutine_WithLoggerFn_Call {
	_c.Call.Return(run)
	return _c
}

// WithRetry provides a mock function for the type GoroutineGoroutine
func (_mock *GoroutineGoroutine) WithRetry(retry int) goroutine.Goroutine {
	ret := _mock.Called(retry)

	if len(ret) == 0 {
		panic("no return value specified for WithRetry")
	}

	var r0 goroutine.Goroutine
	if returnFunc, ok := ret.Get(0).(func(int) goroutine.Goroutine); ok {
		r0 = returnFunc(retry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.Goroutine)
		}
	}
	return r0
}

// GoroutineGoroutine_WithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithRetry'
type GoroutineGoroutine_WithRetry_Call struct {
	*mock.Call
}

// WithRetry is a helper method to define mock.On call
//   - retry int
func (_e *GoroutineGoroutine_Expecter) WithRetry(retry interface{}) *GoroutineGoroutine_WithRetry_Call {
	return &GoroutineGoroutine_WithRetry_Call{Call: _e.mock.On("WithRetry", retry)}
}

func (_c *GoroutineGoroutine_WithRetry_Call) Run(run func(retry int)) *GoroutineGoroutine_WithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineGoroutine_WithRetry_Call) Return(goroutine1 goroutine.Goroutine) *GoroutineGoroutine_WithRetry_Call {
	_c.Call.Return(goroutine1)
	return _c
}

func (_c *GoroutineGoroutine_WithRetry_Call) RunAndReturn(run func(retry int) goroutine.Goroutine) *GoroutineGoroutine_WithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// WithRetryDelay provides a mock function for the type GoroutineGoroutine
func (_mock *GoroutineGoroutine) WithRetryDelay(delay time.Duration) goroutine.Goroutine {
	ret := _mock.Called(delay)

	if len(ret) == 0 {
		panic("no return value specified for WithRetryDelay")
	}

	var r0 goroutine.Goroutine
	if returnFunc, ok := ret.Get(0).(func(time.Duration) goroutine.Goroutine); ok {
		r0 = returnFunc(delay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goroutine.Goroutine)
		}
	}
	return r0
}

// GoroutineGoroutine_WithRetryDelay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithRetryDelay'
type GoroutineGoroutine_WithRetryDelay_Call struct {
	*mock.Call
}

// WithRetryDelay is a helper method to define mock.On call
//   - delay time.Duration
func (_e *GoroutineGoroutine_Expecter) WithRetryDelay(delay interface{}) *GoroutineGoroutine_WithRetryDelay_Call {
	return &GoroutineGoroutine_WithRetryDelay_Call{Call: _e.mock.On("WithRetryDelay", delay)}
}

func (_c *GoroutineGoroutine_WithRetryDelay_Call) Run(run func(delay time.Duration)) *GoroutineGoroutine_WithRetryDelay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GoroutineGoroutine_WithRetryDelay_Call) Return(goroutine1 goroutine.Goroutine) *GoroutineGoroutine_WithRetryDelay_Call {
	_c.Call.Return(goroutine1)
	return _c
}

func (_c *GoroutineGoroutine_WithRetryDelay_Call) RunAndReturn(run func(delay time.Duration) goroutine.Goroutine) *GoroutineGoroutine_WithRetryDelay_Call {
	_c.Call.Return(run)
	return _c
}
