// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/zloevil/jet/grpc"
	grpc0 "google.golang.org/grpc"
)

// NewGrpcTestServiceClient creates a new instance of GrpcTestServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrpcTestServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrpcTestServiceClient {
	mock := &GrpcTestServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GrpcTestServiceClient is an autogenerated mock type for the TestServiceClient type
type GrpcTestServiceClient struct {
	mock.Mock
}

type GrpcTestServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GrpcTestServiceClient) EXPECT() *GrpcTestServiceClient_Expecter {
	return &GrpcTestServiceClient_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type GrpcTestServiceClient
func (_mock *GrpcTestServiceClient) Do(ctx context.Context, in *grpc.Empty, opts ...grpc0.CallOption) (*grpc.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *grpc.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.Empty, ...grpc0.CallOption) (*grpc.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.Empty, ...grpc0.CallOption) *grpc.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc.Empty, ...grpc0.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcTestServiceClient_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type GrpcTestServiceClient_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - in *grpc.Empty
//   - opts ...grpc0.CallOption
func (_e *GrpcTestServiceClient_Expecter) Do(ctx interface{}, in interface{}, opts ...interface{}) *GrpcTestServiceClient_Do_Call {
	return &GrpcTestServiceClient_Do_Call{Call: _e.mock.On("Do",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GrpcTestServiceClient_Do_Call) Run(run func(ctx context.Context, in *grpc.Empty, opts ...grpc0.CallOption)) *GrpcTestServiceClient_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc.Empty
		if args[1] != nil {
			arg1 = args[1].(*grpc.Empty)
		}
		var arg2 []grpc0.CallOption
		var variadicArgs []grpc0.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc0.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *GrpcTestServiceClient_Do_Call) Return(empty *grpc.Empty, err error) *GrpcTestServiceClient_Do_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *GrpcTestServiceClient_Do_Call) RunAndReturn(run func(ctx context.Context, in *grpc.Empty, opts ...grpc0.CallOption) (*grpc.Empty, error)) *GrpcTestServiceClient_Do_Call {
	_c.Call.Return(run)
	return _c
}

// WithError provides a mock function for the type GrpcTestServiceClient
func (_mock *GrpcTestServiceClient) WithError(ctx context.Context, in *grpc.WithErrorRequest, opts ...grpc0.CallOption) (*grpc.WithErrorResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WithError")
	}

	var r0 *grpc.WithErrorResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.WithErrorRequest, ...grpc0.CallOption) (*grpc.WithErrorResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.WithErrorRequest, ...grpc0.CallOption) *grpc.WithErrorResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.WithErrorResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc.WithErrorRequest, ...grpc0.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcTestServiceClient_WithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithError'
type GrpcTestServiceClient_WithError_Call struct {
	*mock.Call
}

// WithError is a helper method to define mock.On call
//   - ctx context.Context
//   - in *grpc.WithErrorRequest
//   - opts ...grpc0.CallOption
func (_e *GrpcTestServiceClient_Expecter) WithError(ctx interface{}, in interface{}, opts ...interface{}) *GrpcTestServiceClient_WithError_Call {
	return &GrpcTestServiceClient_WithError_Call{Call: _e.mock.On("WithError",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GrpcTestServiceClient_WithError_Call) Run(run func(ctx context.Context, in *grpc.WithErrorRequest, opts ...grpc0.CallOption)) *GrpcTestServiceClient_WithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc.WithErrorRequest
		if args[1] != nil {
			arg1 = args[1].(*grpc.WithErrorRequest)
		}
		var arg2 []grpc0.CallOption
		var variadicArgs []grpc0.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc0.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *GrpcTestServiceClient_WithError_Call) Return(withErrorResponse *grpc.WithErrorResponse, err error) *GrpcTestServiceClient_WithError_Call {
	_c.Call.Return(withErrorResponse, err)
	return _c
}

func (_c *GrpcTestServiceClient_WithError_Call) RunAndReturn(run func(ctx context.Context, in *grpc.WithErrorRequest, opts ...grpc0.CallOption) (*grpc.WithErrorResponse, error)) *GrpcTestServiceClient_WithError_Call {
	_c.Call.Return(run)
	return _c
}

// WithPanic provides a mock function for the type GrpcTestServiceClient
func (_mock *GrpcTestServiceClient) WithPanic(ctx context.Context, in *grpc.WithPanicRequest, opts ...grpc0.CallOption) (*grpc.WithPanicResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WithPanic")
	}

	var r0 *grpc.WithPanicResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.WithPanicRequest, ...grpc0.CallOption) (*grpc.WithPanicResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.WithPanicRequest, ...grpc0.CallOption) *grpc.WithPanicResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.WithPanicResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc.WithPanicRequest, ...grpc0.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcTestServiceClient_WithPanic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithPanic'
type GrpcTestServiceClient_WithPanic_Call struct {
	*mock.Call
}

// WithPanic is a helper method to define mock.On call
//   - ctx context.Context
//   - in *grpc.WithPanicRequest
//   - opts ...grpc0.CallOption
func (_e *GrpcTestServiceClient_Expecter) WithPanic(ctx interface{}, in interface{}, opts ...interface{}) *GrpcTestServiceClient_WithPanic_Call {
	return &GrpcTestServiceClient_WithPanic_Call{Call: _e.mock.On("WithPanic",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GrpcTestServiceClient_WithPanic_Call) Run(run func(ctx context.Context, in *grpc.WithPanicRequest, opts ...grpc0.CallOption)) *GrpcTestServiceClient_WithPanic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc.WithPanicRequest
		if args[1] != nil {
			arg1 = args[1].(*grpc.WithPanicRequest)
		}
		var arg2 []grpc0.CallOption
		var variadicArgs []grpc0.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc0.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *GrpcTestServiceClient_WithPanic_Call) Return(withPanicResponse *grpc.WithPanicResponse, err error) *GrpcTestServiceClient_WithPanic_Call {
	_c.Call.Return(withPanicResponse, err)
	return _c
}

func (_c *GrpcTestServiceClient_WithPanic_Call) RunAndReturn(run func(ctx context.Context, in *grpc.WithPanicRequest, opts ...grpc0.CallOption) (*grpc.WithPanicResponse, error)) *GrpcTestServiceClient_WithPanic_Call {
	_c.Call.Return(run)
	return _c
}

// NewGrpcTestServiceServer creates a new instance of GrpcTestServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrpcTestServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrpcTestServiceServer {
	mock := &GrpcTestServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GrpcTestServiceServer is an autogenerated mock type for the TestServiceServer type
type GrpcTestServiceServer struct {
	mock.Mock
}

type GrpcTestServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *GrpcTestServiceServer) EXPECT() *GrpcTestServiceServer_Expecter {
	return &GrpcTestServiceServer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type GrpcTestServiceServer
func (_mock *GrpcTestServiceServer) Do(context1 context.Context, empty *grpc.Empty) (*grpc.Empty, error) {
	ret := _mock.Called(context1, empty)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *grpc.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.Empty) (*grpc.Empty, error)); ok {
		return returnFunc(context1, empty)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.Empty) *grpc.Empty); ok {
		r0 = returnFunc(context1, empty)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc.Empty) error); ok {
		r1 = returnFunc(context1, empty)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcTestServiceServer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type GrpcTestServiceServer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - context1 context.Context
//   - empty *grpc.Empty
func (_e *GrpcTestServiceServer_Expecter) Do(context1 interface{}, empty interface{}) *GrpcTestServiceServer_Do_Call {
	return &GrpcTestServiceServer_Do_Call{Call: _e.mock.On("Do", context1, empty)}
}

func (_c *GrpcTestServiceServer_Do_Call) Run(run func(context1 context.Context, empty *grpc.Empty)) *GrpcTestServiceServer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc.Empty
		if args[1] != nil {
			arg1 = args[1].(*grpc.Empty)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcTestServiceServer_Do_Call) Return(empty1 *grpc.Empty, err error) *GrpcTestServiceServer_Do_Call {
	_c.Call.Return(empty1, err)
	return _c
}

func (_c *GrpcTestServiceServer_Do_Call) RunAndReturn(run func(context1 context.Context, empty *grpc.Empty) (*grpc.Empty, error)) *GrpcTestServiceServer_Do_Call {
	_c.Call.Return(run)
	return _c
}

// WithError provides a mock function for the type GrpcTestServiceServer
func (_mock *GrpcTestServiceServer) WithError(context1 context.Context, withErrorRequest *grpc.WithErrorRequest) (*grpc.WithErrorResponse, error) {
	ret := _mock.Called(context1, withErrorRequest)

	if len(ret) == 0 {
		panic("no return value specified for WithError")
	}

	var r0 *grpc.WithErrorResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.WithErrorRequest) (*grpc.WithErrorResponse, error)); ok {
		return returnFunc(context1, withErrorRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.WithErrorRequest) *grpc.WithErrorResponse); ok {
		r0 = returnFunc(context1, withErrorRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.WithErrorResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc.WithErrorRequest) error); ok {
		r1 = returnFunc(context1, withErrorRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcTestServiceServer_WithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithError'
type GrpcTestServiceServer_WithError_Call struct {
	*mock.Call
}

// WithError is a helper method to define mock.On call
//   - context1 context.Context
//   - withErrorRequest *grpc.WithErrorRequest
func (_e *GrpcTestServiceServer_Expecter) WithError(context1 interface{}, withErrorRequest interface{}) *GrpcTestServiceServer_WithError_Call {
	return &GrpcTestServiceServer_WithError_Call{Call: _e.mock.On("WithError", context1, withErrorRequest)}
}

func (_c *GrpcTestServiceServer_WithError_Call) Run(run func(context1 context.Context, withErrorRequest *grpc.WithErrorRequest)) *GrpcTestServiceServer_WithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc.WithErrorRequest
		if args[1] != nil {
			arg1 = args[1].(*grpc.WithErrorRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcTestServiceServer_WithError_Call) Return(withErrorResponse *grpc.WithErrorResponse, err error) *GrpcTestServiceServer_WithError_Call {
	_c.Call.Return(withErrorResponse, err)
	return _c
}

func (_c *GrpcTestServiceServer_WithError_Call) RunAndReturn(run func(context1 context.Context, withErrorRequest *grpc.WithErrorRequest) (*grpc.WithErrorResponse, error)) *GrpcTestServiceServer_WithError_Call {
	_c.Call.Return(run)
	return _c
}

// WithPanic provides a mock function for the type GrpcTestServiceServer
func (_mock *GrpcTestServiceServer) WithPanic(context1 context.Context, withPanicRequest *grpc.WithPanicRequest) (*grpc.WithPanicResponse, error) {
	ret := _mock.Called(context1, withPanicRequest)

	if len(ret) == 0 {
		panic("no return value specified for WithPanic")
	}

	var r0 *grpc.WithPanicResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.WithPanicRequest) (*grpc.WithPanicResponse, error)); ok {
		return returnFunc(context1, withPanicRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc.WithPanicRequest) *grpc.WithPanicResponse); ok {
		r0 = returnFunc(context1, withPanicRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.WithPanicResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc.WithPanicRequest) error); ok {
		r1 = returnFunc(context1, withPanicRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcTestServiceServer_WithPanic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithPanic'
type GrpcTestServiceServer_WithPanic_Call struct {
	*mock.Call
}

// WithPanic is a helper method to define mock.On call
//   - context1 context.Context
//   - withPanicRequest *grpc.WithPanicRequest
func (_e *GrpcTestServiceServer_Expecter) WithPanic(context1 interface{}, withPanicRequest interface{}) *GrpcTestServiceServer_WithPanic_Call {
	return &GrpcTestServiceServer_WithPanic_Call{Call: _e.mock.On("WithPanic", context1, withPanicRequest)}
}

func (_c *GrpcTestServiceServer_WithPanic_Call) Run(run func(context1 context.Context, withPanicRequest *grpc.WithPanicRequest)) *GrpcTestServiceServer_WithPanic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc.WithPanicRequest
		if args[1] != nil {
			arg1 = args[1].(*grpc.WithPanicRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcTestServiceServer_WithPanic_Call) Return(withPanicResponse *grpc.WithPanicResponse, err error) *GrpcTestServiceServer_WithPanic_Call {
	_c.Call.Return(withPanicResponse, err)
	return _c
}

func (_c *GrpcTestServiceServer_WithPanic_Call) RunAndReturn(run func(context1 context.Context, withPanicRequest *grpc.WithPanicRequest) (*grpc.WithPanicResponse, error)) *GrpcTestServiceServer_WithPanic_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedTestServiceServer provides a mock function for the type GrpcTestServiceServer
func (_mock *GrpcTestServiceServer) mustEmbedUnimplementedTestServiceServer() {
	_mock.Called()
	return
}

// GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedTestServiceServer'
type GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedTestServiceServer is a helper method to define mock.On call
func (_e *GrpcTestServiceServer_Expecter) mustEmbedUnimplementedTestServiceServer() *GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	return &GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedTestServiceServer")}
}

func (_c *GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call) Run(run func()) *GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call) Return() *GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call) RunAndReturn(run func()) *GrpcTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewGrpcUnsafeTestServiceServer creates a new instance of GrpcUnsafeTestServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrpcUnsafeTestServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrpcUnsafeTestServiceServer {
	mock := &GrpcUnsafeTestServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GrpcUnsafeTestServiceServer is an autogenerated mock type for the UnsafeTestServiceServer type
type GrpcUnsafeTestServiceServer struct {
	mock.Mock
}

type GrpcUnsafeTestServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *GrpcUnsafeTestServiceServer) EXPECT() *GrpcUnsafeTestServiceServer_Expecter {
	return &GrpcUnsafeTestServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedTestServiceServer provides a mock function for the type GrpcUnsafeTestServiceServer
func (_mock *GrpcUnsafeTestServiceServer) mustEmbedUnimplementedTestServiceServer() {
	_mock.Called()
	return
}

// GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedTestServiceServer'
type GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedTestServiceServer is a helper method to define mock.On call
func (_e *GrpcUnsafeTestServiceServer_Expecter) mustEmbedUnimplementedTestServiceServer() *GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	return &GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedTestServiceServer")}
}

func (_c *GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call) Run(run func()) *GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call) Return() *GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call) RunAndReturn(run func()) *GrpcUnsafeTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	_c.Run(run)
	return _c
}
