// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/zloevil/jet"
)

// NewJetAppErrBuilder creates a new instance of JetAppErrBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJetAppErrBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *JetAppErrBuilder {
	mock := &JetAppErrBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JetAppErrBuilder is an autogenerated mock type for the AppErrBuilder type
type JetAppErrBuilder struct {
	mock.Mock
}

type JetAppErrBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *JetAppErrBuilder) EXPECT() *JetAppErrBuilder_Expecter {
	return &JetAppErrBuilder_Expecter{mock: &_m.Mock}
}

// Business provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) Business() jet.AppErrBuilder {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Business")
	}

	var r0 jet.AppErrBuilder
	if returnFunc, ok := ret.Get(0).(func() jet.AppErrBuilder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.AppErrBuilder)
		}
	}
	return r0
}

// JetAppErrBuilder_Business_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Business'
type JetAppErrBuilder_Business_Call struct {
	*mock.Call
}

// Business is a helper method to define mock.On call
func (_e *JetAppErrBuilder_Expecter) Business() *JetAppErrBuilder_Business_Call {
	return &JetAppErrBuilder_Business_Call{Call: _e.mock.On("Business")}
}

func (_c *JetAppErrBuilder_Business_Call) Run(run func()) *JetAppErrBuilder_Business_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JetAppErrBuilder_Business_Call) Return(appErrBuilder jet.AppErrBuilder) *JetAppErrBuilder_Business_Call {
	_c.Call.Return(appErrBuilder)
	return _c
}

func (_c *JetAppErrBuilder_Business_Call) RunAndReturn(run func() jet.AppErrBuilder) *JetAppErrBuilder_Business_Call {
	_c.Call.Return(run)
	return _c
}

// C provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) C(ctx context.Context) jet.AppErrBuilder {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for C")
	}

	var r0 jet.AppErrBuilder
	if returnFunc, ok := ret.Get(0).(func(context.Context) jet.AppErrBuilder); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.AppErrBuilder)
		}
	}
	return r0
}

// JetAppErrBuilder_C_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'C'
type JetAppErrBuilder_C_Call struct {
	*mock.Call
}

// C is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JetAppErrBuilder_Expecter) C(ctx interface{}) *JetAppErrBuilder_C_Call {
	return &JetAppErrBuilder_C_Call{Call: _e.mock.On("C", ctx)}
}

func (_c *JetAppErrBuilder_C_Call) Run(run func(ctx context.Context)) *JetAppErrBuilder_C_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetAppErrBuilder_C_Call) Return(appErrBuilder jet.AppErrBuilder) *JetAppErrBuilder_C_Call {
	_c.Call.Return(appErrBuilder)
	return _c
}

func (_c *JetAppErrBuilder_C_Call) RunAndReturn(run func(ctx context.Context) jet.AppErrBuilder) *JetAppErrBuilder_C_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JetAppErrBuilder_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type JetAppErrBuilder_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *JetAppErrBuilder_Expecter) Err() *JetAppErrBuilder_Err_Call {
	return &JetAppErrBuilder_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *JetAppErrBuilder_Err_Call) Run(run func()) *JetAppErrBuilder_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JetAppErrBuilder_Err_Call) Return(err error) *JetAppErrBuilder_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JetAppErrBuilder_Err_Call) RunAndReturn(run func() error) *JetAppErrBuilder_Err_Call {
	_c.Call.Return(run)
	return _c
}

// F provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) F(fields jet.KV) jet.AppErrBuilder {
	ret := _mock.Called(fields)

	if len(ret) == 0 {
		panic("no return value specified for F")
	}

	var r0 jet.AppErrBuilder
	if returnFunc, ok := ret.Get(0).(func(jet.KV) jet.AppErrBuilder); ok {
		r0 = returnFunc(fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.AppErrBuilder)
		}
	}
	return r0
}

// JetAppErrBuilder_F_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'F'
type JetAppErrBuilder_F_Call struct {
	*mock.Call
}

// F is a helper method to define mock.On call
//   - fields jet.KV
func (_e *JetAppErrBuilder_Expecter) F(fields interface{}) *JetAppErrBuilder_F_Call {
	return &JetAppErrBuilder_F_Call{Call: _e.mock.On("F", fields)}
}

func (_c *JetAppErrBuilder_F_Call) Run(run func(fields jet.KV)) *JetAppErrBuilder_F_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jet.KV
		if args[0] != nil {
			arg0 = args[0].(jet.KV)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetAppErrBuilder_F_Call) Return(appErrBuilder jet.AppErrBuilder) *JetAppErrBuilder_F_Call {
	_c.Call.Return(appErrBuilder)
	return _c
}

func (_c *JetAppErrBuilder_F_Call) RunAndReturn(run func(fields jet.KV) jet.AppErrBuilder) *JetAppErrBuilder_F_Call {
	_c.Call.Return(run)
	return _c
}

// GrpcSt provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) GrpcSt(status uint32) jet.AppErrBuilder {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for GrpcSt")
	}

	var r0 jet.AppErrBuilder
	if returnFunc, ok := ret.Get(0).(func(uint32) jet.AppErrBuilder); ok {
		r0 = returnFunc(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.AppErrBuilder)
		}
	}
	return r0
}

// JetAppErrBuilder_GrpcSt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrpcSt'
type JetAppErrBuilder_GrpcSt_Call struct {
	*mock.Call
}

// GrpcSt is a helper method to define mock.On call
//   - status uint32
func (_e *JetAppErrBuilder_Expecter) GrpcSt(status interface{}) *JetAppErrBuilder_GrpcSt_Call {
	return &JetAppErrBuilder_GrpcSt_Call{Call: _e.mock.On("GrpcSt", status)}
}

func (_c *JetAppErrBuilder_GrpcSt_Call) Run(run func(status uint32)) *JetAppErrBuilder_GrpcSt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetAppErrBuilder_GrpcSt_Call) Return(appErrBuilder jet.AppErrBuilder) *JetAppErrBuilder_GrpcSt_Call {
	_c.Call.Return(appErrBuilder)
	return _c
}

func (_c *JetAppErrBuilder_GrpcSt_Call) RunAndReturn(run func(status uint32) jet.AppErrBuilder) *JetAppErrBuilder_GrpcSt_Call {
	_c.Call.Return(run)
	return _c
}

// HttpSt provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) HttpSt(status uint32) jet.AppErrBuilder {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for HttpSt")
	}

	var r0 jet.AppErrBuilder
	if returnFunc, ok := ret.Get(0).(func(uint32) jet.AppErrBuilder); ok {
		r0 = returnFunc(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.AppErrBuilder)
		}
	}
	return r0
}

// JetAppErrBuilder_HttpSt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HttpSt'
type JetAppErrBuilder_HttpSt_Call struct {
	*mock.Call
}

// HttpSt is a helper method to define mock.On call
//   - status uint32
func (_e *JetAppErrBuilder_Expecter) HttpSt(status interface{}) *JetAppErrBuilder_HttpSt_Call {
	return &JetAppErrBuilder_HttpSt_Call{Call: _e.mock.On("HttpSt", status)}
}

func (_c *JetAppErrBuilder_HttpSt_Call) Run(run func(status uint32)) *JetAppErrBuilder_HttpSt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetAppErrBuilder_HttpSt_Call) Return(appErrBuilder jet.AppErrBuilder) *JetAppErrBuilder_HttpSt_Call {
	_c.Call.Return(appErrBuilder)
	return _c
}

func (_c *JetAppErrBuilder_HttpSt_Call) RunAndReturn(run func(status uint32) jet.AppErrBuilder) *JetAppErrBuilder_HttpSt_Call {
	_c.Call.Return(run)
	return _c
}

// Panic provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) Panic() jet.AppErrBuilder {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Panic")
	}

	var r0 jet.AppErrBuilder
	if returnFunc, ok := ret.Get(0).(func() jet.AppErrBuilder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.AppErrBuilder)
		}
	}
	return r0
}

// JetAppErrBuilder_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type JetAppErrBuilder_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
func (_e *JetAppErrBuilder_Expecter) Panic() *JetAppErrBuilder_Panic_Call {
	return &JetAppErrBuilder_Panic_Call{Call: _e.mock.On("Panic")}
}

func (_c *JetAppErrBuilder_Panic_Call) Run(run func()) *JetAppErrBuilder_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JetAppErrBuilder_Panic_Call) Return(appErrBuilder jet.AppErrBuilder) *JetAppErrBuilder_Panic_Call {
	_c.Call.Return(appErrBuilder)
	return _c
}

func (_c *JetAppErrBuilder_Panic_Call) RunAndReturn(run func() jet.AppErrBuilder) *JetAppErrBuilder_Panic_Call {
	_c.Call.Return(run)
	return _c
}

// System provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) System() jet.AppErrBuilder {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for System")
	}

	var r0 jet.AppErrBuilder
	if returnFunc, ok := ret.Get(0).(func() jet.AppErrBuilder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.AppErrBuilder)
		}
	}
	return r0
}

// JetAppErrBuilder_System_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'System'
type JetAppErrBuilder_System_Call struct {
	*mock.Call
}

// System is a helper method to define mock.On call
func (_e *JetAppErrBuilder_Expecter) System() *JetAppErrBuilder_System_Call {
	return &JetAppErrBuilder_System_Call{Call: _e.mock.On("System")}
}

func (_c *JetAppErrBuilder_System_Call) Run(run func()) *JetAppErrBuilder_System_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JetAppErrBuilder_System_Call) Return(appErrBuilder jet.AppErrBuilder) *JetAppErrBuilder_System_Call {
	_c.Call.Return(appErrBuilder)
	return _c
}

func (_c *JetAppErrBuilder_System_Call) RunAndReturn(run func() jet.AppErrBuilder) *JetAppErrBuilder_System_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) Type(t string) jet.AppErrBuilder {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 jet.AppErrBuilder
	if returnFunc, ok := ret.Get(0).(func(string) jet.AppErrBuilder); ok {
		r0 = returnFunc(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.AppErrBuilder)
		}
	}
	return r0
}

// JetAppErrBuilder_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type JetAppErrBuilder_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
//   - t string
func (_e *JetAppErrBuilder_Expecter) Type(t interface{}) *JetAppErrBuilder_Type_Call {
	return &JetAppErrBuilder_Type_Call{Call: _e.mock.On("Type", t)}
}

func (_c *JetAppErrBuilder_Type_Call) Run(run func(t string)) *JetAppErrBuilder_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetAppErrBuilder_Type_Call) Return(appErrBuilder jet.AppErrBuilder) *JetAppErrBuilder_Type_Call {
	_c.Call.Return(appErrBuilder)
	return _c
}

func (_c *JetAppErrBuilder_Type_Call) RunAndReturn(run func(t string) jet.AppErrBuilder) *JetAppErrBuilder_Type_Call {
	_c.Call.Return(run)
	return _c
}

// Wrap provides a mock function for the type JetAppErrBuilder
func (_mock *JetAppErrBuilder) Wrap(cause error) jet.AppErrBuilder {
	ret := _mock.Called(cause)

	if len(ret) == 0 {
		panic("no return value specified for Wrap")
	}

	var r0 jet.AppErrBuilder
	if returnFunc, ok := ret.Get(0).(func(error) jet.AppErrBuilder); ok {
		r0 = returnFunc(cause)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.AppErrBuilder)
		}
	}
	return r0
}

// JetAppErrBuilder_Wrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wrap'
type JetAppErrBuilder_Wrap_Call struct {
	*mock.Call
}

// Wrap is a helper method to define mock.On call
//   - cause error
func (_e *JetAppErrBuilder_Expecter) Wrap(cause interface{}) *JetAppErrBuilder_Wrap_Call {
	return &JetAppErrBuilder_Wrap_Call{Call: _e.mock.On("Wrap", cause)}
}

func (_c *JetAppErrBuilder_Wrap_Call) Run(run func(cause error)) *JetAppErrBuilder_Wrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetAppErrBuilder_Wrap_Call) Return(appErrBuilder jet.AppErrBuilder) *JetAppErrBuilder_Wrap_Call {
	_c.Call.Return(appErrBuilder)
	return _c
}

func (_c *JetAppErrBuilder_Wrap_Call) RunAndReturn(run func(cause error) jet.AppErrBuilder) *JetAppErrBuilder_Wrap_Call {
	_c.Call.Return(run)
	return _c
}

// NewJetAdapter creates a new instance of JetAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJetAdapter[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *JetAdapter[T] {
	mock := &JetAdapter[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JetAdapter is an autogenerated mock type for the Adapter type
type JetAdapter[T any] struct {
	mock.Mock
}

type JetAdapter_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *JetAdapter[T]) EXPECT() *JetAdapter_Expecter[T] {
	return &JetAdapter_Expecter[T]{mock: &_m.Mock}
}

// Close provides a mock function for the type JetAdapter
func (_mock *JetAdapter[T]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JetAdapter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type JetAdapter_Close_Call[T any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JetAdapter_Expecter[T]) Close(ctx interface{}) *JetAdapter_Close_Call[T] {
	return &JetAdapter_Close_Call[T]{Call: _e.mock.On("Close", ctx)}
}

func (_c *JetAdapter_Close_Call[T]) Run(run func(ctx context.Context)) *JetAdapter_Close_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetAdapter_Close_Call[T]) Return(err error) *JetAdapter_Close_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *JetAdapter_Close_Call[T]) RunAndReturn(run func(ctx context.Context) error) *JetAdapter_Close_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type JetAdapter
func (_mock *JetAdapter[T]) Init(ctx context.Context, cfg *T) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JetAdapter_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type JetAdapter_Init_Call[T any] struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg *T
func (_e *JetAdapter_Expecter[T]) Init(ctx interface{}, cfg interface{}) *JetAdapter_Init_Call[T] {
	return &JetAdapter_Init_Call[T]{Call: _e.mock.On("Init", ctx, cfg)}
}

func (_c *JetAdapter_Init_Call[T]) Run(run func(ctx context.Context, cfg *T)) *JetAdapter_Init_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *T
		if args[1] != nil {
			arg1 = args[1].(*T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JetAdapter_Init_Call[T]) Return(err error) *JetAdapter_Init_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *JetAdapter_Init_Call[T]) RunAndReturn(run func(ctx context.Context, cfg *T) error) *JetAdapter_Init_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewJetAdapterListener creates a new instance of JetAdapterListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJetAdapterListener[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *JetAdapterListener[T] {
	mock := &JetAdapterListener[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JetAdapterListener is an autogenerated mock type for the AdapterListener type
type JetAdapterListener[T any] struct {
	mock.Mock
}

type JetAdapterListener_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *JetAdapterListener[T]) EXPECT() *JetAdapterListener_Expecter[T] {
	return &JetAdapterListener_Expecter[T]{mock: &_m.Mock}
}

// Close provides a mock function for the type JetAdapterListener
func (_mock *JetAdapterListener[T]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JetAdapterListener_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type JetAdapterListener_Close_Call[T any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JetAdapterListener_Expecter[T]) Close(ctx interface{}) *JetAdapterListener_Close_Call[T] {
	return &JetAdapterListener_Close_Call[T]{Call: _e.mock.On("Close", ctx)}
}

func (_c *JetAdapterListener_Close_Call[T]) Run(run func(ctx context.Context)) *JetAdapterListener_Close_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetAdapterListener_Close_Call[T]) Return(err error) *JetAdapterListener_Close_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *JetAdapterListener_Close_Call[T]) RunAndReturn(run func(ctx context.Context) error) *JetAdapterListener_Close_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type JetAdapterListener
func (_mock *JetAdapterListener[T]) Init(ctx context.Context, cfg *T) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JetAdapterListener_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type JetAdapterListener_Init_Call[T any] struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg *T
func (_e *JetAdapterListener_Expecter[T]) Init(ctx interface{}, cfg interface{}) *JetAdapterListener_Init_Call[T] {
	return &JetAdapterListener_Init_Call[T]{Call: _e.mock.On("Init", ctx, cfg)}
}

func (_c *JetAdapterListener_Init_Call[T]) Run(run func(ctx context.Context, cfg *T)) *JetAdapterListener_Init_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *T
		if args[1] != nil {
			arg1 = args[1].(*T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JetAdapterListener_Init_Call[T]) Return(err error) *JetAdapterListener_Init_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *JetAdapterListener_Init_Call[T]) RunAndReturn(run func(ctx context.Context, cfg *T) error) *JetAdapterListener_Init_Call[T] {
	_c.Call.Return(run)
	return _c
}

// ListenAsync provides a mock function for the type JetAdapterListener
func (_mock *JetAdapterListener[T]) ListenAsync(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListenAsync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JetAdapterListener_ListenAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAsync'
type JetAdapterListener_ListenAsync_Call[T any] struct {
	*mock.Call
}

// ListenAsync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JetAdapterListener_Expecter[T]) ListenAsync(ctx interface{}) *JetAdapterListener_ListenAsync_Call[T] {
	return &JetAdapterListener_ListenAsync_Call[T]{Call: _e.mock.On("ListenAsync", ctx)}
}

func (_c *JetAdapterListener_ListenAsync_Call[T]) Run(run func(ctx context.Context)) *JetAdapterListener_ListenAsync_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetAdapterListener_ListenAsync_Call[T]) Return(err error) *JetAdapterListener_ListenAsync_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *JetAdapterListener_ListenAsync_Call[T]) RunAndReturn(run func(ctx context.Context) error) *JetAdapterListener_ListenAsync_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewJetSearchable creates a new instance of JetSearchable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJetSearchable[TItem any, Rq any](t interface {
	mock.TestingT
	Cleanup(func())
}) *JetSearchable[TItem, Rq] {
	mock := &JetSearchable[TItem, Rq]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JetSearchable is an autogenerated mock type for the Searchable type
type JetSearchable[TItem any, Rq any] struct {
	mock.Mock
}

type JetSearchable_Expecter[TItem any, Rq any] struct {
	mock *mock.Mock
}

func (_m *JetSearchable[TItem, Rq]) EXPECT() *JetSearchable_Expecter[TItem, Rq] {
	return &JetSearchable_Expecter[TItem, Rq]{mock: &_m.Mock}
}

// Search provides a mock function for the type JetSearchable
func (_mock *JetSearchable[TItem, Rq]) Search(ctx context.Context, rq jet.PagingRequestG[Rq]) (jet.PagingResponseG[TItem], error) {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 jet.PagingResponseG[TItem]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jet.PagingRequestG[Rq]) (jet.PagingResponseG[TItem], error)); ok {
		return returnFunc(ctx, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, jet.PagingRequestG[Rq]) jet.PagingResponseG[TItem]); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		r0 = ret.Get(0).(jet.PagingResponseG[TItem])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, jet.PagingRequestG[Rq]) error); ok {
		r1 = returnFunc(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JetSearchable_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type JetSearchable_Search_Call[TItem any, Rq any] struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - rq jet.PagingRequestG[Rq]
func (_e *JetSearchable_Expecter[TItem, Rq]) Search(ctx interface{}, rq interface{}) *JetSearchable_Search_Call[TItem, Rq] {
	return &JetSearchable_Search_Call[TItem, Rq]{Call: _e.mock.On("Search", ctx, rq)}
}

func (_c *JetSearchable_Search_Call[TItem, Rq]) Run(run func(ctx context.Context, rq jet.PagingRequestG[Rq])) *JetSearchable_Search_Call[TItem, Rq] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jet.PagingRequestG[Rq]
		if args[1] != nil {
			arg1 = args[1].(jet.PagingRequestG[Rq])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JetSearchable_Search_Call[TItem, Rq]) Return(pagingResponseG jet.PagingResponseG[TItem], err error) *JetSearchable_Search_Call[TItem, Rq] {
	_c.Call.Return(pagingResponseG, err)
	return _c
}

func (_c *JetSearchable_Search_Call[TItem, Rq]) RunAndReturn(run func(ctx context.Context, rq jet.PagingRequestG[Rq]) (jet.PagingResponseG[TItem], error)) *JetSearchable_Search_Call[TItem, Rq] {
	_c.Call.Return(run)
	return _c
}

// NewJetErrorHook creates a new instance of JetErrorHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJetErrorHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *JetErrorHook {
	mock := &JetErrorHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JetErrorHook is an autogenerated mock type for the ErrorHook type
type JetErrorHook struct {
	mock.Mock
}

type JetErrorHook_Expecter struct {
	mock *mock.Mock
}

func (_m *JetErrorHook) EXPECT() *JetErrorHook_Expecter {
	return &JetErrorHook_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type JetErrorHook
func (_mock *JetErrorHook) Error(err error) {
	_mock.Called(err)
	return
}

// JetErrorHook_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type JetErrorHook_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
func (_e *JetErrorHook_Expecter) Error(err interface{}) *JetErrorHook_Error_Call {
	return &JetErrorHook_Error_Call{Call: _e.mock.On("Error", err)}
}

func (_c *JetErrorHook_Error_Call) Run(run func(err error)) *JetErrorHook_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetErrorHook_Error_Call) Return() *JetErrorHook_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *JetErrorHook_Error_Call) RunAndReturn(run func(err error)) *JetErrorHook_Error_Call {
	_c.Run(run)
	return _c
}

// NewJetCLogger creates a new instance of JetCLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJetCLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *JetCLogger {
	mock := &JetCLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JetCLogger is an autogenerated mock type for the CLogger type
type JetCLogger struct {
	mock.Mock
}

type JetCLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *JetCLogger) EXPECT() *JetCLogger_Expecter {
	return &JetCLogger_Expecter{mock: &_m.Mock}
}

// C provides a mock function for the type JetCLogger
func (_mock *JetCLogger) C(ctx context.Context) jet.CLogger {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for C")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(context.Context) jet.CLogger); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_C_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'C'
type JetCLogger_C_Call struct {
	*mock.Call
}

// C is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JetCLogger_Expecter) C(ctx interface{}) *JetCLogger_C_Call {
	return &JetCLogger_C_Call{Call: _e.mock.On("C", ctx)}
}

func (_c *JetCLogger_C_Call) Run(run func(ctx context.Context)) *JetCLogger_C_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetCLogger_C_Call) Return(cLogger jet.CLogger) *JetCLogger_C_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_C_Call) RunAndReturn(run func(ctx context.Context) jet.CLogger) *JetCLogger_C_Call {
	_c.Call.Return(run)
	return _c
}

// Clone provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Clone() jet.CLogger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func() jet.CLogger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type JetCLogger_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
func (_e *JetCLogger_Expecter) Clone() *JetCLogger_Clone_Call {
	return &JetCLogger_Clone_Call{Call: _e.mock.On("Clone")}
}

func (_c *JetCLogger_Clone_Call) Run(run func()) *JetCLogger_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JetCLogger_Clone_Call) Return(cLogger jet.CLogger) *JetCLogger_Clone_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Clone_Call) RunAndReturn(run func() jet.CLogger) *JetCLogger_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// Cmp provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Cmp(c string) jet.CLogger {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Cmp")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string) jet.CLogger); ok {
		r0 = returnFunc(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Cmp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cmp'
type JetCLogger_Cmp_Call struct {
	*mock.Call
}

// Cmp is a helper method to define mock.On call
//   - c string
func (_e *JetCLogger_Expecter) Cmp(c interface{}) *JetCLogger_Cmp_Call {
	return &JetCLogger_Cmp_Call{Call: _e.mock.On("Cmp", c)}
}

func (_c *JetCLogger_Cmp_Call) Run(run func(c string)) *JetCLogger_Cmp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetCLogger_Cmp_Call) Return(cLogger jet.CLogger) *JetCLogger_Cmp_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Cmp_Call) RunAndReturn(run func(c string) jet.CLogger) *JetCLogger_Cmp_Call {
	_c.Call.Return(run)
	return _c
}

// Dbg provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Dbg(args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Dbg")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(...interface{}) jet.CLogger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Dbg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dbg'
type JetCLogger_Dbg_Call struct {
	*mock.Call
}

// Dbg is a helper method to define mock.On call
//   - args ...interface{}
func (_e *JetCLogger_Expecter) Dbg(args ...interface{}) *JetCLogger_Dbg_Call {
	return &JetCLogger_Dbg_Call{Call: _e.mock.On("Dbg",
		append([]interface{}{}, args...)...)}
}

func (_c *JetCLogger_Dbg_Call) Run(run func(args ...interface{})) *JetCLogger_Dbg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *JetCLogger_Dbg_Call) Return(cLogger jet.CLogger) *JetCLogger_Dbg_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Dbg_Call) RunAndReturn(run func(args ...interface{}) jet.CLogger) *JetCLogger_Dbg_Call {
	_c.Call.Return(run)
	return _c
}

// DbgF provides a mock function for the type JetCLogger
func (_mock *JetCLogger) DbgF(format string, args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(format, args)
	} else {
		tmpRet = _mock.Called(format)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DbgF")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) jet.CLogger); ok {
		r0 = returnFunc(format, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_DbgF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DbgF'
type JetCLogger_DbgF_Call struct {
	*mock.Call
}

// DbgF is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *JetCLogger_Expecter) DbgF(format interface{}, args ...interface{}) *JetCLogger_DbgF_Call {
	return &JetCLogger_DbgF_Call{Call: _e.mock.On("DbgF",
		append([]interface{}{format}, args...)...)}
}

func (_c *JetCLogger_DbgF_Call) Run(run func(format string, args ...interface{})) *JetCLogger_DbgF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *JetCLogger_DbgF_Call) Return(cLogger jet.CLogger) *JetCLogger_DbgF_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_DbgF_Call) RunAndReturn(run func(format string, args ...interface{}) jet.CLogger) *JetCLogger_DbgF_Call {
	_c.Call.Return(run)
	return _c
}

// E provides a mock function for the type JetCLogger
func (_mock *JetCLogger) E(err error) jet.CLogger {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for E")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(error) jet.CLogger); ok {
		r0 = returnFunc(err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_E_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'E'
type JetCLogger_E_Call struct {
	*mock.Call
}

// E is a helper method to define mock.On call
//   - err error
func (_e *JetCLogger_Expecter) E(err interface{}) *JetCLogger_E_Call {
	return &JetCLogger_E_Call{Call: _e.mock.On("E", err)}
}

func (_c *JetCLogger_E_Call) Run(run func(err error)) *JetCLogger_E_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetCLogger_E_Call) Return(cLogger jet.CLogger) *JetCLogger_E_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_E_Call) RunAndReturn(run func(err error) jet.CLogger) *JetCLogger_E_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Err(args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(...interface{}) jet.CLogger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type JetCLogger_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
//   - args ...interface{}
func (_e *JetCLogger_Expecter) Err(args ...interface{}) *JetCLogger_Err_Call {
	return &JetCLogger_Err_Call{Call: _e.mock.On("Err",
		append([]interface{}{}, args...)...)}
}

func (_c *JetCLogger_Err_Call) Run(run func(args ...interface{})) *JetCLogger_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *JetCLogger_Err_Call) Return(cLogger jet.CLogger) *JetCLogger_Err_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Err_Call) RunAndReturn(run func(args ...interface{}) jet.CLogger) *JetCLogger_Err_Call {
	_c.Call.Return(run)
	return _c
}

// ErrF provides a mock function for the type JetCLogger
func (_mock *JetCLogger) ErrF(format string, args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(format, args)
	} else {
		tmpRet = _mock.Called(format)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ErrF")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) jet.CLogger); ok {
		r0 = returnFunc(format, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_ErrF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrF'
type JetCLogger_ErrF_Call struct {
	*mock.Call
}

// ErrF is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *JetCLogger_Expecter) ErrF(format interface{}, args ...interface{}) *JetCLogger_ErrF_Call {
	return &JetCLogger_ErrF_Call{Call: _e.mock.On("ErrF",
		append([]interface{}{format}, args...)...)}
}

func (_c *JetCLogger_ErrF_Call) Run(run func(format string, args ...interface{})) *JetCLogger_ErrF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *JetCLogger_ErrF_Call) Return(cLogger jet.CLogger) *JetCLogger_ErrF_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_ErrF_Call) RunAndReturn(run func(format string, args ...interface{}) jet.CLogger) *JetCLogger_ErrF_Call {
	_c.Call.Return(run)
	return _c
}

// F provides a mock function for the type JetCLogger
func (_mock *JetCLogger) F(fields jet.KV) jet.CLogger {
	ret := _mock.Called(fields)

	if len(ret) == 0 {
		panic("no return value specified for F")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(jet.KV) jet.CLogger); ok {
		r0 = returnFunc(fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_F_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'F'
type JetCLogger_F_Call struct {
	*mock.Call
}

// F is a helper method to define mock.On call
//   - fields jet.KV
func (_e *JetCLogger_Expecter) F(fields interface{}) *JetCLogger_F_Call {
	return &JetCLogger_F_Call{Call: _e.mock.On("F", fields)}
}

func (_c *JetCLogger_F_Call) Run(run func(fields jet.KV)) *JetCLogger_F_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jet.KV
		if args[0] != nil {
			arg0 = args[0].(jet.KV)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetCLogger_F_Call) Return(cLogger jet.CLogger) *JetCLogger_F_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_F_Call) RunAndReturn(run func(fields jet.KV) jet.CLogger) *JetCLogger_F_Call {
	_c.Call.Return(run)
	return _c
}

// Fatal provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Fatal(args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Fatal")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(...interface{}) jet.CLogger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type JetCLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - args ...interface{}
func (_e *JetCLogger_Expecter) Fatal(args ...interface{}) *JetCLogger_Fatal_Call {
	return &JetCLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{}, args...)...)}
}

func (_c *JetCLogger_Fatal_Call) Run(run func(args ...interface{})) *JetCLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *JetCLogger_Fatal_Call) Return(cLogger jet.CLogger) *JetCLogger_Fatal_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Fatal_Call) RunAndReturn(run func(args ...interface{}) jet.CLogger) *JetCLogger_Fatal_Call {
	_c.Call.Return(run)
	return _c
}

// FatalF provides a mock function for the type JetCLogger
func (_mock *JetCLogger) FatalF(format string, args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(format, args)
	} else {
		tmpRet = _mock.Called(format)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FatalF")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) jet.CLogger); ok {
		r0 = returnFunc(format, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_FatalF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FatalF'
type JetCLogger_FatalF_Call struct {
	*mock.Call
}

// FatalF is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *JetCLogger_Expecter) FatalF(format interface{}, args ...interface{}) *JetCLogger_FatalF_Call {
	return &JetCLogger_FatalF_Call{Call: _e.mock.On("FatalF",
		append([]interface{}{format}, args...)...)}
}

func (_c *JetCLogger_FatalF_Call) Run(run func(format string, args ...interface{})) *JetCLogger_FatalF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *JetCLogger_FatalF_Call) Return(cLogger jet.CLogger) *JetCLogger_FatalF_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_FatalF_Call) RunAndReturn(run func(format string, args ...interface{}) jet.CLogger) *JetCLogger_FatalF_Call {
	_c.Call.Return(run)
	return _c
}

// Inf provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Inf(args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Inf")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(...interface{}) jet.CLogger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Inf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inf'
type JetCLogger_Inf_Call struct {
	*mock.Call
}

// Inf is a helper method to define mock.On call
//   - args ...interface{}
func (_e *JetCLogger_Expecter) Inf(args ...interface{}) *JetCLogger_Inf_Call {
	return &JetCLogger_Inf_Call{Call: _e.mock.On("Inf",
		append([]interface{}{}, args...)...)}
}

func (_c *JetCLogger_Inf_Call) Run(run func(args ...interface{})) *JetCLogger_Inf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *JetCLogger_Inf_Call) Return(cLogger jet.CLogger) *JetCLogger_Inf_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Inf_Call) RunAndReturn(run func(args ...interface{}) jet.CLogger) *JetCLogger_Inf_Call {
	_c.Call.Return(run)
	return _c
}

// InfF provides a mock function for the type JetCLogger
func (_mock *JetCLogger) InfF(format string, args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(format, args)
	} else {
		tmpRet = _mock.Called(format)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InfF")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) jet.CLogger); ok {
		r0 = returnFunc(format, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_InfF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfF'
type JetCLogger_InfF_Call struct {
	*mock.Call
}

// InfF is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *JetCLogger_Expecter) InfF(format interface{}, args ...interface{}) *JetCLogger_InfF_Call {
	return &JetCLogger_InfF_Call{Call: _e.mock.On("InfF",
		append([]interface{}{format}, args...)...)}
}

func (_c *JetCLogger_InfF_Call) Run(run func(format string, args ...interface{})) *JetCLogger_InfF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *JetCLogger_InfF_Call) Return(cLogger jet.CLogger) *JetCLogger_InfF_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_InfF_Call) RunAndReturn(run func(format string, args ...interface{}) jet.CLogger) *JetCLogger_InfF_Call {
	_c.Call.Return(run)
	return _c
}

// Mth provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Mth(m string) jet.CLogger {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Mth")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string) jet.CLogger); ok {
		r0 = returnFunc(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Mth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mth'
type JetCLogger_Mth_Call struct {
	*mock.Call
}

// Mth is a helper method to define mock.On call
//   - m string
func (_e *JetCLogger_Expecter) Mth(m interface{}) *JetCLogger_Mth_Call {
	return &JetCLogger_Mth_Call{Call: _e.mock.On("Mth", m)}
}

func (_c *JetCLogger_Mth_Call) Run(run func(m string)) *JetCLogger_Mth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetCLogger_Mth_Call) Return(cLogger jet.CLogger) *JetCLogger_Mth_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Mth_Call) RunAndReturn(run func(m string) jet.CLogger) *JetCLogger_Mth_Call {
	_c.Call.Return(run)
	return _c
}

// Node provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Node(n string) jet.CLogger {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Node")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string) jet.CLogger); ok {
		r0 = returnFunc(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Node_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Node'
type JetCLogger_Node_Call struct {
	*mock.Call
}

// Node is a helper method to define mock.On call
//   - n string
func (_e *JetCLogger_Expecter) Node(n interface{}) *JetCLogger_Node_Call {
	return &JetCLogger_Node_Call{Call: _e.mock.On("Node", n)}
}

func (_c *JetCLogger_Node_Call) Run(run func(n string)) *JetCLogger_Node_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetCLogger_Node_Call) Return(cLogger jet.CLogger) *JetCLogger_Node_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Node_Call) RunAndReturn(run func(n string) jet.CLogger) *JetCLogger_Node_Call {
	_c.Call.Return(run)
	return _c
}

// Pr provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Pr(m string) jet.CLogger {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Pr")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string) jet.CLogger); ok {
		r0 = returnFunc(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Pr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pr'
type JetCLogger_Pr_Call struct {
	*mock.Call
}

// Pr is a helper method to define mock.On call
//   - m string
func (_e *JetCLogger_Expecter) Pr(m interface{}) *JetCLogger_Pr_Call {
	return &JetCLogger_Pr_Call{Call: _e.mock.On("Pr", m)}
}

func (_c *JetCLogger_Pr_Call) Run(run func(m string)) *JetCLogger_Pr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetCLogger_Pr_Call) Return(cLogger jet.CLogger) *JetCLogger_Pr_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Pr_Call) RunAndReturn(run func(m string) jet.CLogger) *JetCLogger_Pr_Call {
	_c.Call.Return(run)
	return _c
}

// Printf provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Printf(s string, ifaceVals ...interface{}) {
	if len(ifaceVals) > 0 {
		_mock.Called(s, ifaceVals)
	} else {
		_mock.Called(s)
	}

	return
}

// JetCLogger_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type JetCLogger_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - s string
//   - ifaceVals ...interface{}
func (_e *JetCLogger_Expecter) Printf(s interface{}, ifaceVals ...interface{}) *JetCLogger_Printf_Call {
	return &JetCLogger_Printf_Call{Call: _e.mock.On("Printf",
		append([]interface{}{s}, ifaceVals...)...)}
}

func (_c *JetCLogger_Printf_Call) Run(run func(s string, ifaceVals ...interface{})) *JetCLogger_Printf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *JetCLogger_Printf_Call) Return() *JetCLogger_Printf_Call {
	_c.Call.Return()
	return _c
}

func (_c *JetCLogger_Printf_Call) RunAndReturn(run func(s string, ifaceVals ...interface{})) *JetCLogger_Printf_Call {
	_c.Run(run)
	return _c
}

// PrintfErr provides a mock function for the type JetCLogger
func (_mock *JetCLogger) PrintfErr(f string, args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(f, args)
	} else {
		_mock.Called(f)
	}

	return
}

// JetCLogger_PrintfErr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintfErr'
type JetCLogger_PrintfErr_Call struct {
	*mock.Call
}

// PrintfErr is a helper method to define mock.On call
//   - f string
//   - args ...interface{}
func (_e *JetCLogger_Expecter) PrintfErr(f interface{}, args ...interface{}) *JetCLogger_PrintfErr_Call {
	return &JetCLogger_PrintfErr_Call{Call: _e.mock.On("PrintfErr",
		append([]interface{}{f}, args...)...)}
}

func (_c *JetCLogger_PrintfErr_Call) Run(run func(f string, args ...interface{})) *JetCLogger_PrintfErr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *JetCLogger_PrintfErr_Call) Return() *JetCLogger_PrintfErr_Call {
	_c.Call.Return()
	return _c
}

func (_c *JetCLogger_PrintfErr_Call) RunAndReturn(run func(f string, args ...interface{})) *JetCLogger_PrintfErr_Call {
	_c.Run(run)
	return _c
}

// Srv provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Srv(s string) jet.CLogger {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Srv")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string) jet.CLogger); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Srv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Srv'
type JetCLogger_Srv_Call struct {
	*mock.Call
}

// Srv is a helper method to define mock.On call
//   - s string
func (_e *JetCLogger_Expecter) Srv(s interface{}) *JetCLogger_Srv_Call {
	return &JetCLogger_Srv_Call{Call: _e.mock.On("Srv", s)}
}

func (_c *JetCLogger_Srv_Call) Run(run func(s string)) *JetCLogger_Srv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetCLogger_Srv_Call) Return(cLogger jet.CLogger) *JetCLogger_Srv_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Srv_Call) RunAndReturn(run func(s string) jet.CLogger) *JetCLogger_Srv_Call {
	_c.Call.Return(run)
	return _c
}

// St provides a mock function for the type JetCLogger
func (_mock *JetCLogger) St() jet.CLogger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for St")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func() jet.CLogger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_St_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'St'
type JetCLogger_St_Call struct {
	*mock.Call
}

// St is a helper method to define mock.On call
func (_e *JetCLogger_Expecter) St() *JetCLogger_St_Call {
	return &JetCLogger_St_Call{Call: _e.mock.On("St")}
}

func (_c *JetCLogger_St_Call) Run(run func()) *JetCLogger_St_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JetCLogger_St_Call) Return(cLogger jet.CLogger) *JetCLogger_St_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_St_Call) RunAndReturn(run func() jet.CLogger) *JetCLogger_St_Call {
	_c.Call.Return(run)
	return _c
}

// Trc provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Trc(args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Trc")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(...interface{}) jet.CLogger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Trc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trc'
type JetCLogger_Trc_Call struct {
	*mock.Call
}

// Trc is a helper method to define mock.On call
//   - args ...interface{}
func (_e *JetCLogger_Expecter) Trc(args ...interface{}) *JetCLogger_Trc_Call {
	return &JetCLogger_Trc_Call{Call: _e.mock.On("Trc",
		append([]interface{}{}, args...)...)}
}

func (_c *JetCLogger_Trc_Call) Run(run func(args ...interface{})) *JetCLogger_Trc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *JetCLogger_Trc_Call) Return(cLogger jet.CLogger) *JetCLogger_Trc_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Trc_Call) RunAndReturn(run func(args ...interface{}) jet.CLogger) *JetCLogger_Trc_Call {
	_c.Call.Return(run)
	return _c
}

// TrcF provides a mock function for the type JetCLogger
func (_mock *JetCLogger) TrcF(format string, args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(format, args)
	} else {
		tmpRet = _mock.Called(format)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for TrcF")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) jet.CLogger); ok {
		r0 = returnFunc(format, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_TrcF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrcF'
type JetCLogger_TrcF_Call struct {
	*mock.Call
}

// TrcF is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *JetCLogger_Expecter) TrcF(format interface{}, args ...interface{}) *JetCLogger_TrcF_Call {
	return &JetCLogger_TrcF_Call{Call: _e.mock.On("TrcF",
		append([]interface{}{format}, args...)...)}
}

func (_c *JetCLogger_TrcF_Call) Run(run func(format string, args ...interface{})) *JetCLogger_TrcF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *JetCLogger_TrcF_Call) Return(cLogger jet.CLogger) *JetCLogger_TrcF_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_TrcF_Call) RunAndReturn(run func(format string, args ...interface{}) jet.CLogger) *JetCLogger_TrcF_Call {
	_c.Call.Return(run)
	return _c
}

// TrcObj provides a mock function for the type JetCLogger
func (_mock *JetCLogger) TrcObj(format string, args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(format, args)
	} else {
		tmpRet = _mock.Called(format)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for TrcObj")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) jet.CLogger); ok {
		r0 = returnFunc(format, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_TrcObj_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrcObj'
type JetCLogger_TrcObj_Call struct {
	*mock.Call
}

// TrcObj is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *JetCLogger_Expecter) TrcObj(format interface{}, args ...interface{}) *JetCLogger_TrcObj_Call {
	return &JetCLogger_TrcObj_Call{Call: _e.mock.On("TrcObj",
		append([]interface{}{format}, args...)...)}
}

func (_c *JetCLogger_TrcObj_Call) Run(run func(format string, args ...interface{})) *JetCLogger_TrcObj_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *JetCLogger_TrcObj_Call) Return(cLogger jet.CLogger) *JetCLogger_TrcObj_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_TrcObj_Call) RunAndReturn(run func(format string, args ...interface{}) jet.CLogger) *JetCLogger_TrcObj_Call {
	_c.Call.Return(run)
	return _c
}

// Warn provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Warn(args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Warn")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(...interface{}) jet.CLogger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type JetCLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - args ...interface{}
func (_e *JetCLogger_Expecter) Warn(args ...interface{}) *JetCLogger_Warn_Call {
	return &JetCLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{}, args...)...)}
}

func (_c *JetCLogger_Warn_Call) Run(run func(args ...interface{})) *JetCLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *JetCLogger_Warn_Call) Return(cLogger jet.CLogger) *JetCLogger_Warn_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_Warn_Call) RunAndReturn(run func(args ...interface{}) jet.CLogger) *JetCLogger_Warn_Call {
	_c.Call.Return(run)
	return _c
}

// WarnF provides a mock function for the type JetCLogger
func (_mock *JetCLogger) WarnF(format string, args ...interface{}) jet.CLogger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(format, args)
	} else {
		tmpRet = _mock.Called(format)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WarnF")
	}

	var r0 jet.CLogger
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) jet.CLogger); ok {
		r0 = returnFunc(format, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jet.CLogger)
		}
	}
	return r0
}

// JetCLogger_WarnF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnF'
type JetCLogger_WarnF_Call struct {
	*mock.Call
}

// WarnF is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *JetCLogger_Expecter) WarnF(format interface{}, args ...interface{}) *JetCLogger_WarnF_Call {
	return &JetCLogger_WarnF_Call{Call: _e.mock.On("WarnF",
		append([]interface{}{format}, args...)...)}
}

func (_c *JetCLogger_WarnF_Call) Run(run func(format string, args ...interface{})) *JetCLogger_WarnF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *JetCLogger_WarnF_Call) Return(cLogger jet.CLogger) *JetCLogger_WarnF_Call {
	_c.Call.Return(cLogger)
	return _c
}

func (_c *JetCLogger_WarnF_Call) RunAndReturn(run func(format string, args ...interface{}) jet.CLogger) *JetCLogger_WarnF_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type JetCLogger
func (_mock *JetCLogger) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JetCLogger_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type JetCLogger_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *JetCLogger_Expecter) Write(p interface{}) *JetCLogger_Write_Call {
	return &JetCLogger_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *JetCLogger_Write_Call) Run(run func(p []byte)) *JetCLogger_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JetCLogger_Write_Call) Return(n int, err error) *JetCLogger_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *JetCLogger_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *JetCLogger_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewJetPageReader creates a new instance of JetPageReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJetPageReader[TItem any, TRq any](t interface {
	mock.TestingT
	Cleanup(func())
}) *JetPageReader[TItem, TRq] {
	mock := &JetPageReader[TItem, TRq]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JetPageReader is an autogenerated mock type for the PageReader type
type JetPageReader[TItem any, TRq any] struct {
	mock.Mock
}

type JetPageReader_Expecter[TItem any, TRq any] struct {
	mock *mock.Mock
}

func (_m *JetPageReader[TItem, TRq]) EXPECT() *JetPageReader_Expecter[TItem, TRq] {
	return &JetPageReader_Expecter[TItem, TRq]{mock: &_m.Mock}
}

// GetPage provides a mock function for the type JetPageReader
func (_mock *JetPageReader[TItem, TRq]) GetPage(ctx context.Context, rq TRq) chan jet.PagingResponseG[TItem] {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 chan jet.PagingResponseG[TItem]
	if returnFunc, ok := ret.Get(0).(func(context.Context, TRq) chan jet.PagingResponseG[TItem]); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan jet.PagingResponseG[TItem])
		}
	}
	return r0
}

// JetPageReader_GetPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPage'
type JetPageReader_GetPage_Call[TItem any, TRq any] struct {
	*mock.Call
}

// GetPage is a helper method to define mock.On call
//   - ctx context.Context
//   - rq TRq
func (_e *JetPageReader_Expecter[TItem, TRq]) GetPage(ctx interface{}, rq interface{}) *JetPageReader_GetPage_Call[TItem, TRq] {
	return &JetPageReader_GetPage_Call[TItem, TRq]{Call: _e.mock.On("GetPage", ctx, rq)}
}

func (_c *JetPageReader_GetPage_Call[TItem, TRq]) Run(run func(ctx context.Context, rq TRq)) *JetPageReader_GetPage_Call[TItem, TRq] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TRq
		if args[1] != nil {
			arg1 = args[1].(TRq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JetPageReader_GetPage_Call[TItem, TRq]) Return(pagingResponseGCh chan jet.PagingResponseG[TItem]) *JetPageReader_GetPage_Call[TItem, TRq] {
	_c.Call.Return(pagingResponseGCh)
	return _c
}

func (_c *JetPageReader_GetPage_Call[TItem, TRq]) RunAndReturn(run func(ctx context.Context, rq TRq) chan jet.PagingResponseG[TItem]) *JetPageReader_GetPage_Call[TItem, TRq] {
	_c.Call.Return(run)
	return _c
}
