// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMemcacheMemCache creates a new instance of MemcacheMemCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemcacheMemCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemcacheMemCache {
	mock := &MemcacheMemCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MemcacheMemCache is an autogenerated mock type for the MemCache type
type MemcacheMemCache struct {
	mock.Mock
}

type MemcacheMemCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MemcacheMemCache) EXPECT() *MemcacheMemCache_Expecter {
	return &MemcacheMemCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MemcacheMemCache
func (_mock *MemcacheMemCache) Delete(key string) {
	_mock.Called(key)
	return
}

// MemcacheMemCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MemcacheMemCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key
func (_e *MemcacheMemCache_Expecter) Delete(key interface{}) *MemcacheMemCache_Delete_Call {
	return &MemcacheMemCache_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MemcacheMemCache_Delete_Call) Run(run func(key string)) *MemcacheMemCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MemcacheMemCache_Delete_Call) Return() *MemcacheMemCache_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MemcacheMemCache_Delete_Call) RunAndReturn(run func(key string)) *MemcacheMemCache_Delete_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MemcacheMemCache
func (_mock *MemcacheMemCache) Get(key string) (interface{}, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (interface{}, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MemcacheMemCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MemcacheMemCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key
func (_e *MemcacheMemCache_Expecter) Get(key interface{}) *MemcacheMemCache_Get_Call {
	return &MemcacheMemCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MemcacheMemCache_Get_Call) Run(run func(key string)) *MemcacheMemCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MemcacheMemCache_Get_Call) Return(ifaceVal interface{}, b bool) *MemcacheMemCache_Get_Call {
	_c.Call.Return(ifaceVal, b)
	return _c
}

func (_c *MemcacheMemCache_Get_Call) RunAndReturn(run func(key string) (interface{}, bool)) *MemcacheMemCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MemcacheMemCache
func (_mock *MemcacheMemCache) Set(key string, v interface{}, ttl time.Duration) {
	_mock.Called(key, v, ttl)
	return
}

// MemcacheMemCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MemcacheMemCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key
//   - v
//   - ttl
func (_e *MemcacheMemCache_Expecter) Set(key interface{}, v interface{}, ttl interface{}) *MemcacheMemCache_Set_Call {
	return &MemcacheMemCache_Set_Call{Call: _e.mock.On("Set", key, v, ttl)}
}

func (_c *MemcacheMemCache_Set_Call) Run(run func(key string, v interface{}, ttl time.Duration)) *MemcacheMemCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}), args[2].(time.Duration))
	})
	return _c
}

func (_c *MemcacheMemCache_Set_Call) Return() *MemcacheMemCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MemcacheMemCache_Set_Call) RunAndReturn(run func(key string, v interface{}, ttl time.Duration)) *MemcacheMemCache_Set_Call {
	_c.Run(run)
	return _c
}
