// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMigrationMigration creates a new instance of MigrationMigration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMigrationMigration(t interface {
	mock.TestingT
	Cleanup(func())
}) *MigrationMigration {
	mock := &MigrationMigration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MigrationMigration is an autogenerated mock type for the Migration type
type MigrationMigration struct {
	mock.Mock
}

type MigrationMigration_Expecter struct {
	mock *mock.Mock
}

func (_m *MigrationMigration) EXPECT() *MigrationMigration_Expecter {
	return &MigrationMigration_Expecter{mock: &_m.Mock}
}

// Down provides a mock function for the type MigrationMigration
func (_mock *MigrationMigration) Down() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MigrationMigration_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type MigrationMigration_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
func (_e *MigrationMigration_Expecter) Down() *MigrationMigration_Down_Call {
	return &MigrationMigration_Down_Call{Call: _e.mock.On("Down")}
}

func (_c *MigrationMigration_Down_Call) Run(run func()) *MigrationMigration_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MigrationMigration_Down_Call) Return(err error) *MigrationMigration_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MigrationMigration_Down_Call) RunAndReturn(run func() error) *MigrationMigration_Down_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type MigrationMigration
func (_mock *MigrationMigration) Up() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MigrationMigration_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MigrationMigration_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
func (_e *MigrationMigration_Expecter) Up() *MigrationMigration_Up_Call {
	return &MigrationMigration_Up_Call{Call: _e.mock.On("Up")}
}

func (_c *MigrationMigration_Up_Call) Run(run func()) *MigrationMigration_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MigrationMigration_Up_Call) Return(err error) *MigrationMigration_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MigrationMigration_Up_Call) RunAndReturn(run func() error) *MigrationMigration_Up_Call {
	_c.Call.Return(run)
	return _c
}
