// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/zloevil/jet/monitoring"
)

// NewMonitoringErrorMonitoring creates a new instance of MonitoringErrorMonitoring. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoringErrorMonitoring(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringErrorMonitoring {
	mock := &MonitoringErrorMonitoring{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MonitoringErrorMonitoring is an autogenerated mock type for the ErrorMonitoring type
type MonitoringErrorMonitoring struct {
	mock.Mock
}

type MonitoringErrorMonitoring_Expecter struct {
	mock *mock.Mock
}

func (_m *MonitoringErrorMonitoring) EXPECT() *MonitoringErrorMonitoring_Expecter {
	return &MonitoringErrorMonitoring_Expecter{mock: &_m.Mock}
}

// BusinessErrorInc provides a mock function for the type MonitoringErrorMonitoring
func (_mock *MonitoringErrorMonitoring) BusinessErrorInc(errCode string) {
	_mock.Called(errCode)
	return
}

// MonitoringErrorMonitoring_BusinessErrorInc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BusinessErrorInc'
type MonitoringErrorMonitoring_BusinessErrorInc_Call struct {
	*mock.Call
}

// BusinessErrorInc is a helper method to define mock.On call
//   - errCode string
func (_e *MonitoringErrorMonitoring_Expecter) BusinessErrorInc(errCode interface{}) *MonitoringErrorMonitoring_BusinessErrorInc_Call {
	return &MonitoringErrorMonitoring_BusinessErrorInc_Call{Call: _e.mock.On("BusinessErrorInc", errCode)}
}

func (_c *MonitoringErrorMonitoring_BusinessErrorInc_Call) Run(run func(errCode string)) *MonitoringErrorMonitoring_BusinessErrorInc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MonitoringErrorMonitoring_BusinessErrorInc_Call) Return() *MonitoringErrorMonitoring_BusinessErrorInc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MonitoringErrorMonitoring_BusinessErrorInc_Call) RunAndReturn(run func(errCode string)) *MonitoringErrorMonitoring_BusinessErrorInc_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MonitoringErrorMonitoring
func (_mock *MonitoringErrorMonitoring) Error(err error) {
	_mock.Called(err)
	return
}

// MonitoringErrorMonitoring_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MonitoringErrorMonitoring_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
func (_e *MonitoringErrorMonitoring_Expecter) Error(err interface{}) *MonitoringErrorMonitoring_Error_Call {
	return &MonitoringErrorMonitoring_Error_Call{Call: _e.mock.On("Error", err)}
}

func (_c *MonitoringErrorMonitoring_Error_Call) Run(run func(err error)) *MonitoringErrorMonitoring_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MonitoringErrorMonitoring_Error_Call) Return() *MonitoringErrorMonitoring_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MonitoringErrorMonitoring_Error_Call) RunAndReturn(run func(err error)) *MonitoringErrorMonitoring_Error_Call {
	_c.Run(run)
	return _c
}

// GetCollector provides a mock function for the type MonitoringErrorMonitoring
func (_mock *MonitoringErrorMonitoring) GetCollector() monitoring.MetricsCollector {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCollector")
	}

	var r0 monitoring.MetricsCollector
	if returnFunc, ok := ret.Get(0).(func() monitoring.MetricsCollector); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(monitoring.MetricsCollector)
		}
	}
	return r0
}

// MonitoringErrorMonitoring_GetCollector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollector'
type MonitoringErrorMonitoring_GetCollector_Call struct {
	*mock.Call
}

// GetCollector is a helper method to define mock.On call
func (_e *MonitoringErrorMonitoring_Expecter) GetCollector() *MonitoringErrorMonitoring_GetCollector_Call {
	return &MonitoringErrorMonitoring_GetCollector_Call{Call: _e.mock.On("GetCollector")}
}

func (_c *MonitoringErrorMonitoring_GetCollector_Call) Run(run func()) *MonitoringErrorMonitoring_GetCollector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MonitoringErrorMonitoring_GetCollector_Call) Return(metricsCollector monitoring.MetricsCollector) *MonitoringErrorMonitoring_GetCollector_Call {
	_c.Call.Return(metricsCollector)
	return _c
}

func (_c *MonitoringErrorMonitoring_GetCollector_Call) RunAndReturn(run func() monitoring.MetricsCollector) *MonitoringErrorMonitoring_GetCollector_Call {
	_c.Call.Return(run)
	return _c
}

// PanicInc provides a mock function for the type MonitoringErrorMonitoring
func (_mock *MonitoringErrorMonitoring) PanicInc() {
	_mock.Called()
	return
}

// MonitoringErrorMonitoring_PanicInc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PanicInc'
type MonitoringErrorMonitoring_PanicInc_Call struct {
	*mock.Call
}

// PanicInc is a helper method to define mock.On call
func (_e *MonitoringErrorMonitoring_Expecter) PanicInc() *MonitoringErrorMonitoring_PanicInc_Call {
	return &MonitoringErrorMonitoring_PanicInc_Call{Call: _e.mock.On("PanicInc")}
}

func (_c *MonitoringErrorMonitoring_PanicInc_Call) Run(run func()) *MonitoringErrorMonitoring_PanicInc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MonitoringErrorMonitoring_PanicInc_Call) Return() *MonitoringErrorMonitoring_PanicInc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MonitoringErrorMonitoring_PanicInc_Call) RunAndReturn(run func()) *MonitoringErrorMonitoring_PanicInc_Call {
	_c.Run(run)
	return _c
}

// SystemErrorInc provides a mock function for the type MonitoringErrorMonitoring
func (_mock *MonitoringErrorMonitoring) SystemErrorInc(errCode string) {
	_mock.Called(errCode)
	return
}

// MonitoringErrorMonitoring_SystemErrorInc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SystemErrorInc'
type MonitoringErrorMonitoring_SystemErrorInc_Call struct {
	*mock.Call
}

// SystemErrorInc is a helper method to define mock.On call
//   - errCode string
func (_e *MonitoringErrorMonitoring_Expecter) SystemErrorInc(errCode interface{}) *MonitoringErrorMonitoring_SystemErrorInc_Call {
	return &MonitoringErrorMonitoring_SystemErrorInc_Call{Call: _e.mock.On("SystemErrorInc", errCode)}
}

func (_c *MonitoringErrorMonitoring_SystemErrorInc_Call) Run(run func(errCode string)) *MonitoringErrorMonitoring_SystemErrorInc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MonitoringErrorMonitoring_SystemErrorInc_Call) Return() *MonitoringErrorMonitoring_SystemErrorInc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MonitoringErrorMonitoring_SystemErrorInc_Call) RunAndReturn(run func(errCode string)) *MonitoringErrorMonitoring_SystemErrorInc_Call {
	_c.Run(run)
	return _c
}

// NewMonitoringMetricsProvider creates a new instance of MonitoringMetricsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoringMetricsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringMetricsProvider {
	mock := &MonitoringMetricsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MonitoringMetricsProvider is an autogenerated mock type for the MetricsProvider type
type MonitoringMetricsProvider struct {
	mock.Mock
}

type MonitoringMetricsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MonitoringMetricsProvider) EXPECT() *MonitoringMetricsProvider_Expecter {
	return &MonitoringMetricsProvider_Expecter{mock: &_m.Mock}
}

// GetCollector provides a mock function for the type MonitoringMetricsProvider
func (_mock *MonitoringMetricsProvider) GetCollector() monitoring.MetricsCollector {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCollector")
	}

	var r0 monitoring.MetricsCollector
	if returnFunc, ok := ret.Get(0).(func() monitoring.MetricsCollector); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(monitoring.MetricsCollector)
		}
	}
	return r0
}

// MonitoringMetricsProvider_GetCollector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollector'
type MonitoringMetricsProvider_GetCollector_Call struct {
	*mock.Call
}

// GetCollector is a helper method to define mock.On call
func (_e *MonitoringMetricsProvider_Expecter) GetCollector() *MonitoringMetricsProvider_GetCollector_Call {
	return &MonitoringMetricsProvider_GetCollector_Call{Call: _e.mock.On("GetCollector")}
}

func (_c *MonitoringMetricsProvider_GetCollector_Call) Run(run func()) *MonitoringMetricsProvider_GetCollector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MonitoringMetricsProvider_GetCollector_Call) Return(metricsCollector monitoring.MetricsCollector) *MonitoringMetricsProvider_GetCollector_Call {
	_c.Call.Return(metricsCollector)
	return _c
}

func (_c *MonitoringMetricsProvider_GetCollector_Call) RunAndReturn(run func() monitoring.MetricsCollector) *MonitoringMetricsProvider_GetCollector_Call {
	_c.Call.Return(run)
	return _c
}

// NewMonitoringMetricsServer creates a new instance of MonitoringMetricsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoringMetricsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringMetricsServer {
	mock := &MonitoringMetricsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MonitoringMetricsServer is an autogenerated mock type for the MetricsServer type
type MonitoringMetricsServer struct {
	mock.Mock
}

type MonitoringMetricsServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MonitoringMetricsServer) EXPECT() *MonitoringMetricsServer_Expecter {
	return &MonitoringMetricsServer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MonitoringMetricsServer
func (_mock *MonitoringMetricsServer) Close() {
	_mock.Called()
	return
}

// MonitoringMetricsServer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MonitoringMetricsServer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MonitoringMetricsServer_Expecter) Close() *MonitoringMetricsServer_Close_Call {
	return &MonitoringMetricsServer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MonitoringMetricsServer_Close_Call) Run(run func()) *MonitoringMetricsServer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MonitoringMetricsServer_Close_Call) Return() *MonitoringMetricsServer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MonitoringMetricsServer_Close_Call) RunAndReturn(run func()) *MonitoringMetricsServer_Close_Call {
	_c.Run(run)
	return _c
}

// Init provides a mock function for the type MonitoringMetricsServer
func (_mock *MonitoringMetricsServer) Init(config *monitoring.Config, MetricProviders ...monitoring.MetricsProvider) error {
	var tmpRet mock.Arguments
	if len(MetricProviders) > 0 {
		tmpRet = _mock.Called(config, MetricProviders)
	} else {
		tmpRet = _mock.Called(config)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*monitoring.Config, ...monitoring.MetricsProvider) error); ok {
		r0 = returnFunc(config, MetricProviders...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MonitoringMetricsServer_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MonitoringMetricsServer_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - config *monitoring.Config
//   - MetricProviders ...monitoring.MetricsProvider
func (_e *MonitoringMetricsServer_Expecter) Init(config interface{}, MetricProviders ...interface{}) *MonitoringMetricsServer_Init_Call {
	return &MonitoringMetricsServer_Init_Call{Call: _e.mock.On("Init",
		append([]interface{}{config}, MetricProviders...)...)}
}

func (_c *MonitoringMetricsServer_Init_Call) Run(run func(config *monitoring.Config, MetricProviders ...monitoring.MetricsProvider)) *MonitoringMetricsServer_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *monitoring.Config
		if args[0] != nil {
			arg0 = args[0].(*monitoring.Config)
		}
		var arg1 []monitoring.MetricsProvider
		var variadicArgs []monitoring.MetricsProvider
		if len(args) > 1 {
			variadicArgs = args[1].([]monitoring.MetricsProvider)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MonitoringMetricsServer_Init_Call) Return(err error) *MonitoringMetricsServer_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MonitoringMetricsServer_Init_Call) RunAndReturn(run func(config *monitoring.Config, MetricProviders ...monitoring.MetricsProvider) error) *MonitoringMetricsServer_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Listen provides a mock function for the type MonitoringMetricsServer
func (_mock *MonitoringMetricsServer) Listen() {
	_mock.Called()
	return
}

// MonitoringMetricsServer_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type MonitoringMetricsServer_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
func (_e *MonitoringMetricsServer_Expecter) Listen() *MonitoringMetricsServer_Listen_Call {
	return &MonitoringMetricsServer_Listen_Call{Call: _e.mock.On("Listen")}
}

func (_c *MonitoringMetricsServer_Listen_Call) Run(run func()) *MonitoringMetricsServer_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MonitoringMetricsServer_Listen_Call) Return() *MonitoringMetricsServer_Listen_Call {
	_c.Call.Return()
	return _c
}

func (_c *MonitoringMetricsServer_Listen_Call) RunAndReturn(run func()) *MonitoringMetricsServer_Listen_Call {
	_c.Run(run)
	return _c
}

// NewMonitoringRegexpMonitoring creates a new instance of MonitoringRegexpMonitoring. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoringRegexpMonitoring(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringRegexpMonitoring {
	mock := &MonitoringRegexpMonitoring{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MonitoringRegexpMonitoring is an autogenerated mock type for the RegexpMonitoring type
type MonitoringRegexpMonitoring struct {
	mock.Mock
}

type MonitoringRegexpMonitoring_Expecter struct {
	mock *mock.Mock
}

func (_m *MonitoringRegexpMonitoring) EXPECT() *MonitoringRegexpMonitoring_Expecter {
	return &MonitoringRegexpMonitoring_Expecter{mock: &_m.Mock}
}

// AddRegexps provides a mock function for the type MonitoringRegexpMonitoring
func (_mock *MonitoringRegexpMonitoring) AddRegexps(regexps ...*monitoring.Regexp) {
	if len(regexps) > 0 {
		_mock.Called(regexps)
	} else {
		_mock.Called()
	}

	return
}

// MonitoringRegexpMonitoring_AddRegexps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRegexps'
type MonitoringRegexpMonitoring_AddRegexps_Call struct {
	*mock.Call
}

// AddRegexps is a helper method to define mock.On call
//   - regexps ...*monitoring.Regexp
func (_e *MonitoringRegexpMonitoring_Expecter) AddRegexps(regexps ...interface{}) *MonitoringRegexpMonitoring_AddRegexps_Call {
	return &MonitoringRegexpMonitoring_AddRegexps_Call{Call: _e.mock.On("AddRegexps",
		append([]interface{}{}, regexps...)...)}
}

func (_c *MonitoringRegexpMonitoring_AddRegexps_Call) Run(run func(regexps ...*monitoring.Regexp)) *MonitoringRegexpMonitoring_AddRegexps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*monitoring.Regexp
		var variadicArgs []*monitoring.Regexp
		if len(args) > 0 {
			variadicArgs = args[0].([]*monitoring.Regexp)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MonitoringRegexpMonitoring_AddRegexps_Call) Return() *MonitoringRegexpMonitoring_AddRegexps_Call {
	_c.Call.Return()
	return _c
}

func (_c *MonitoringRegexpMonitoring_AddRegexps_Call) RunAndReturn(run func(regexps ...*monitoring.Regexp)) *MonitoringRegexpMonitoring_AddRegexps_Call {
	_c.Run(run)
	return _c
}

// GetCollector provides a mock function for the type MonitoringRegexpMonitoring
func (_mock *MonitoringRegexpMonitoring) GetCollector() monitoring.MetricsCollector {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCollector")
	}

	var r0 monitoring.MetricsCollector
	if returnFunc, ok := ret.Get(0).(func() monitoring.MetricsCollector); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(monitoring.MetricsCollector)
		}
	}
	return r0
}

// MonitoringRegexpMonitoring_GetCollector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollector'
type MonitoringRegexpMonitoring_GetCollector_Call struct {
	*mock.Call
}

// GetCollector is a helper method to define mock.On call
func (_e *MonitoringRegexpMonitoring_Expecter) GetCollector() *MonitoringRegexpMonitoring_GetCollector_Call {
	return &MonitoringRegexpMonitoring_GetCollector_Call{Call: _e.mock.On("GetCollector")}
}

func (_c *MonitoringRegexpMonitoring_GetCollector_Call) Run(run func()) *MonitoringRegexpMonitoring_GetCollector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MonitoringRegexpMonitoring_GetCollector_Call) Return(metricsCollector monitoring.MetricsCollector) *MonitoringRegexpMonitoring_GetCollector_Call {
	_c.Call.Return(metricsCollector)
	return _c
}

func (_c *MonitoringRegexpMonitoring_GetCollector_Call) RunAndReturn(run func() monitoring.MetricsCollector) *MonitoringRegexpMonitoring_GetCollector_Call {
	_c.Call.Return(run)
	return _c
}

// Text provides a mock function for the type MonitoringRegexpMonitoring
func (_mock *MonitoringRegexpMonitoring) Text(text string) {
	_mock.Called(text)
	return
}

// MonitoringRegexpMonitoring_Text_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Text'
type MonitoringRegexpMonitoring_Text_Call struct {
	*mock.Call
}

// Text is a helper method to define mock.On call
//   - text string
func (_e *MonitoringRegexpMonitoring_Expecter) Text(text interface{}) *MonitoringRegexpMonitoring_Text_Call {
	return &MonitoringRegexpMonitoring_Text_Call{Call: _e.mock.On("Text", text)}
}

func (_c *MonitoringRegexpMonitoring_Text_Call) Run(run func(text string)) *MonitoringRegexpMonitoring_Text_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MonitoringRegexpMonitoring_Text_Call) Return() *MonitoringRegexpMonitoring_Text_Call {
	_c.Call.Return()
	return _c
}

func (_c *MonitoringRegexpMonitoring_Text_Call) RunAndReturn(run func(text string)) *MonitoringRegexpMonitoring_Text_Call {
	_c.Run(run)
	return _c
}
