// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/zloevil/jet/notification"
)

// NewNotificationBuilder creates a new instance of NotificationBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationBuilder[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationBuilder[T] {
	mock := &NotificationBuilder[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationBuilder is an autogenerated mock type for the Builder type
type NotificationBuilder[T any] struct {
	mock.Mock
}

type NotificationBuilder_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *NotificationBuilder[T]) EXPECT() *NotificationBuilder_Expecter[T] {
	return &NotificationBuilder_Expecter[T]{mock: &_m.Mock}
}

// B provides a mock function for the type NotificationBuilder
func (_mock *NotificationBuilder[T]) B(msg *T) *notification.Notification[T] {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for B")
	}

	var r0 *notification.Notification[T]
	if returnFunc, ok := ret.Get(0).(func(*T) *notification.Notification[T]); ok {
		r0 = returnFunc(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notification.Notification[T])
		}
	}
	return r0
}

// NotificationBuilder_B_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'B'
type NotificationBuilder_B_Call[T any] struct {
	*mock.Call
}

// B is a helper method to define mock.On call
//   - msg
func (_e *NotificationBuilder_Expecter[T]) B(msg interface{}) *NotificationBuilder_B_Call[T] {
	return &NotificationBuilder_B_Call[T]{Call: _e.mock.On("B", msg)}
}

func (_c *NotificationBuilder_B_Call[T]) Run(run func(msg *T)) *NotificationBuilder_B_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*T))
	})
	return _c
}

func (_c *NotificationBuilder_B_Call[T]) Return(notification1 *notification.Notification[T]) *NotificationBuilder_B_Call[T] {
	_c.Call.Return(notification1)
	return _c
}

func (_c *NotificationBuilder_B_Call[T]) RunAndReturn(run func(msg *T) *notification.Notification[T]) *NotificationBuilder_B_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Receivers provides a mock function for the type NotificationBuilder
func (_mock *NotificationBuilder[T]) Receivers(receivers []*notification.Receiver) notification.Builder[T] {
	ret := _mock.Called(receivers)

	if len(ret) == 0 {
		panic("no return value specified for Receivers")
	}

	var r0 notification.Builder[T]
	if returnFunc, ok := ret.Get(0).(func([]*notification.Receiver) notification.Builder[T]); ok {
		r0 = returnFunc(receivers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notification.Builder[T])
		}
	}
	return r0
}

// NotificationBuilder_Receivers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receivers'
type NotificationBuilder_Receivers_Call[T any] struct {
	*mock.Call
}

// Receivers is a helper method to define mock.On call
//   - receivers
func (_e *NotificationBuilder_Expecter[T]) Receivers(receivers interface{}) *NotificationBuilder_Receivers_Call[T] {
	return &NotificationBuilder_Receivers_Call[T]{Call: _e.mock.On("Receivers", receivers)}
}

func (_c *NotificationBuilder_Receivers_Call[T]) Run(run func(receivers []*notification.Receiver)) *NotificationBuilder_Receivers_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*notification.Receiver))
	})
	return _c
}

func (_c *NotificationBuilder_Receivers_Call[T]) Return(builder notification.Builder[T]) *NotificationBuilder_Receivers_Call[T] {
	_c.Call.Return(builder)
	return _c
}

func (_c *NotificationBuilder_Receivers_Call[T]) RunAndReturn(run func(receivers []*notification.Receiver) notification.Builder[T]) *NotificationBuilder_Receivers_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Types provides a mock function for the type NotificationBuilder
func (_mock *NotificationBuilder[T]) Types(types ...string) notification.Builder[T] {
	var tmpRet mock.Arguments
	if len(types) > 0 {
		tmpRet = _mock.Called(types)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Types")
	}

	var r0 notification.Builder[T]
	if returnFunc, ok := ret.Get(0).(func(...string) notification.Builder[T]); ok {
		r0 = returnFunc(types...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notification.Builder[T])
		}
	}
	return r0
}

// NotificationBuilder_Types_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Types'
type NotificationBuilder_Types_Call[T any] struct {
	*mock.Call
}

// Types is a helper method to define mock.On call
//   - types
func (_e *NotificationBuilder_Expecter[T]) Types(types ...interface{}) *NotificationBuilder_Types_Call[T] {
	return &NotificationBuilder_Types_Call[T]{Call: _e.mock.On("Types",
		append([]interface{}{}, types...)...)}
}

func (_c *NotificationBuilder_Types_Call[T]) Run(run func(types ...string)) *NotificationBuilder_Types_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]string)
		run(variadicArgs...)
	})
	return _c
}

func (_c *NotificationBuilder_Types_Call[T]) Return(builder notification.Builder[T]) *NotificationBuilder_Types_Call[T] {
	_c.Call.Return(builder)
	return _c
}

func (_c *NotificationBuilder_Types_Call[T]) RunAndReturn(run func(types ...string) notification.Builder[T]) *NotificationBuilder_Types_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewNotificationReceivers creates a new instance of NotificationReceivers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationReceivers(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationReceivers {
	mock := &NotificationReceivers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationReceivers is an autogenerated mock type for the Receivers type
type NotificationReceivers struct {
	mock.Mock
}

type NotificationReceivers_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationReceivers) EXPECT() *NotificationReceivers_Expecter {
	return &NotificationReceivers_Expecter{mock: &_m.Mock}
}

// B provides a mock function for the type NotificationReceivers
func (_mock *NotificationReceivers) B() ([]*notification.Receiver, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for B")
	}

	var r0 []*notification.Receiver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*notification.Receiver, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*notification.Receiver); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*notification.Receiver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationReceivers_B_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'B'
type NotificationReceivers_B_Call struct {
	*mock.Call
}

// B is a helper method to define mock.On call
func (_e *NotificationReceivers_Expecter) B() *NotificationReceivers_B_Call {
	return &NotificationReceivers_B_Call{Call: _e.mock.On("B")}
}

func (_c *NotificationReceivers_B_Call) Run(run func()) *NotificationReceivers_B_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NotificationReceivers_B_Call) Return(receivers []*notification.Receiver, err error) *NotificationReceivers_B_Call {
	_c.Call.Return(receivers, err)
	return _c
}

func (_c *NotificationReceivers_B_Call) RunAndReturn(run func() ([]*notification.Receiver, error)) *NotificationReceivers_B_Call {
	_c.Call.Return(run)
	return _c
}

// Permissions provides a mock function for the type NotificationReceivers
func (_mock *NotificationReceivers) Permissions(resolver notification.Resolver) notification.Receivers {
	ret := _mock.Called(resolver)

	if len(ret) == 0 {
		panic("no return value specified for Permissions")
	}

	var r0 notification.Receivers
	if returnFunc, ok := ret.Get(0).(func(notification.Resolver) notification.Receivers); ok {
		r0 = returnFunc(resolver)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notification.Receivers)
		}
	}
	return r0
}

// NotificationReceivers_Permissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Permissions'
type NotificationReceivers_Permissions_Call struct {
	*mock.Call
}

// Permissions is a helper method to define mock.On call
//   - resolver
func (_e *NotificationReceivers_Expecter) Permissions(resolver interface{}) *NotificationReceivers_Permissions_Call {
	return &NotificationReceivers_Permissions_Call{Call: _e.mock.On("Permissions", resolver)}
}

func (_c *NotificationReceivers_Permissions_Call) Run(run func(resolver notification.Resolver)) *NotificationReceivers_Permissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Resolver))
	})
	return _c
}

func (_c *NotificationReceivers_Permissions_Call) Return(receivers notification.Receivers) *NotificationReceivers_Permissions_Call {
	_c.Call.Return(receivers)
	return _c
}

func (_c *NotificationReceivers_Permissions_Call) RunAndReturn(run func(resolver notification.Resolver) notification.Receivers) *NotificationReceivers_Permissions_Call {
	_c.Call.Return(run)
	return _c
}

// Scopes provides a mock function for the type NotificationReceivers
func (_mock *NotificationReceivers) Scopes(fns ...notification.ReceiverFn) notification.Receivers {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(fns)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Scopes")
	}

	var r0 notification.Receivers
	if returnFunc, ok := ret.Get(0).(func(...notification.ReceiverFn) notification.Receivers); ok {
		r0 = returnFunc(fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notification.Receivers)
		}
	}
	return r0
}

// NotificationReceivers_Scopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scopes'
type NotificationReceivers_Scopes_Call struct {
	*mock.Call
}

// Scopes is a helper method to define mock.On call
//   - fns
func (_e *NotificationReceivers_Expecter) Scopes(fns ...interface{}) *NotificationReceivers_Scopes_Call {
	return &NotificationReceivers_Scopes_Call{Call: _e.mock.On("Scopes",
		append([]interface{}{}, fns...)...)}
}

func (_c *NotificationReceivers_Scopes_Call) Run(run func(fns ...notification.ReceiverFn)) *NotificationReceivers_Scopes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]notification.ReceiverFn)
		run(variadicArgs...)
	})
	return _c
}

func (_c *NotificationReceivers_Scopes_Call) Return(receivers notification.Receivers) *NotificationReceivers_Scopes_Call {
	_c.Call.Return(receivers)
	return _c
}

func (_c *NotificationReceivers_Scopes_Call) RunAndReturn(run func(fns ...notification.ReceiverFn) notification.Receivers) *NotificationReceivers_Scopes_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationResolver creates a new instance of NotificationResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationResolver {
	mock := &NotificationResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationResolver is an autogenerated mock type for the Resolver type
type NotificationResolver struct {
	mock.Mock
}

type NotificationResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationResolver) EXPECT() *NotificationResolver_Expecter {
	return &NotificationResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type NotificationResolver
func (_mock *NotificationResolver) Resolve() *notification.PermissionsRequest {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 *notification.PermissionsRequest
	if returnFunc, ok := ret.Get(0).(func() *notification.PermissionsRequest); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notification.PermissionsRequest)
		}
	}
	return r0
}

// NotificationResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type NotificationResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
func (_e *NotificationResolver_Expecter) Resolve() *NotificationResolver_Resolve_Call {
	return &NotificationResolver_Resolve_Call{Call: _e.mock.On("Resolve")}
}

func (_c *NotificationResolver_Resolve_Call) Run(run func()) *NotificationResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NotificationResolver_Resolve_Call) Return(permissionsRequest *notification.PermissionsRequest) *NotificationResolver_Resolve_Call {
	_c.Call.Return(permissionsRequest)
	return _c
}

func (_c *NotificationResolver_Resolve_Call) RunAndReturn(run func() *notification.PermissionsRequest) *NotificationResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
