// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/zloevil/jet/profile"
)

// NewProfileServer creates a new instance of ProfileServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileServer {
	mock := &ProfileServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProfileServer is an autogenerated mock type for the Server type
type ProfileServer struct {
	mock.Mock
}

type ProfileServer_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileServer) EXPECT() *ProfileServer_Expecter {
	return &ProfileServer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ProfileServer
func (_mock *ProfileServer) Close() {
	_mock.Called()
	return
}

// ProfileServer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ProfileServer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ProfileServer_Expecter) Close() *ProfileServer_Close_Call {
	return &ProfileServer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ProfileServer_Close_Call) Run(run func()) *ProfileServer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProfileServer_Close_Call) Return() *ProfileServer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProfileServer_Close_Call) RunAndReturn(run func()) *ProfileServer_Close_Call {
	_c.Run(run)
	return _c
}

// Init provides a mock function for the type ProfileServer
func (_mock *ProfileServer) Init(config *profile.Config) error {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*profile.Config) error); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileServer_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type ProfileServer_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - config *profile.Config
func (_e *ProfileServer_Expecter) Init(config interface{}) *ProfileServer_Init_Call {
	return &ProfileServer_Init_Call{Call: _e.mock.On("Init", config)}
}

func (_c *ProfileServer_Init_Call) Run(run func(config *profile.Config)) *ProfileServer_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *profile.Config
		if args[0] != nil {
			arg0 = args[0].(*profile.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProfileServer_Init_Call) Return(err error) *ProfileServer_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileServer_Init_Call) RunAndReturn(run func(config *profile.Config) error) *ProfileServer_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Listen provides a mock function for the type ProfileServer
func (_mock *ProfileServer) Listen() {
	_mock.Called()
	return
}

// ProfileServer_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type ProfileServer_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
func (_e *ProfileServer_Expecter) Listen() *ProfileServer_Listen_Call {
	return &ProfileServer_Listen_Call{Call: _e.mock.On("Listen")}
}

func (_c *ProfileServer_Listen_Call) Run(run func()) *ProfileServer_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProfileServer_Listen_Call) Return() *ProfileServer_Listen_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProfileServer_Listen_Call) RunAndReturn(run func()) *ProfileServer_Listen_Call {
	_c.Run(run)
	return _c
}
