// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewRedisPriorityQueue creates a new instance of RedisPriorityQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisPriorityQueue[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisPriorityQueue[T] {
	mock := &RedisPriorityQueue[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RedisPriorityQueue is an autogenerated mock type for the PriorityQueue type
type RedisPriorityQueue[T any] struct {
	mock.Mock
}

type RedisPriorityQueue_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *RedisPriorityQueue[T]) EXPECT() *RedisPriorityQueue_Expecter[T] {
	return &RedisPriorityQueue_Expecter[T]{mock: &_m.Mock}
}

// Pop provides a mock function for the type RedisPriorityQueue
func (_mock *RedisPriorityQueue[T]) Pop(ctx context.Context, numItems int) ([]T, error) {
	ret := _mock.Called(ctx, numItems)

	if len(ret) == 0 {
		panic("no return value specified for Pop")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]T, error)); ok {
		return returnFunc(ctx, numItems)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []T); ok {
		r0 = returnFunc(ctx, numItems)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, numItems)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisPriorityQueue_Pop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pop'
type RedisPriorityQueue_Pop_Call[T any] struct {
	*mock.Call
}

// Pop is a helper method to define mock.On call
//   - ctx
//   - numItems
func (_e *RedisPriorityQueue_Expecter[T]) Pop(ctx interface{}, numItems interface{}) *RedisPriorityQueue_Pop_Call[T] {
	return &RedisPriorityQueue_Pop_Call[T]{Call: _e.mock.On("Pop", ctx, numItems)}
}

func (_c *RedisPriorityQueue_Pop_Call[T]) Run(run func(ctx context.Context, numItems int)) *RedisPriorityQueue_Pop_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *RedisPriorityQueue_Pop_Call[T]) Return(vs []T, err error) *RedisPriorityQueue_Pop_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *RedisPriorityQueue_Pop_Call[T]) RunAndReturn(run func(ctx context.Context, numItems int) ([]T, error)) *RedisPriorityQueue_Pop_Call[T] {
	_c.Call.Return(run)
	return _c
}

// PopManyAndRemove provides a mock function for the type RedisPriorityQueue
func (_mock *RedisPriorityQueue[T]) PopManyAndRemove(ctx context.Context, numItems int) ([]T, error) {
	ret := _mock.Called(ctx, numItems)

	if len(ret) == 0 {
		panic("no return value specified for PopManyAndRemove")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]T, error)); ok {
		return returnFunc(ctx, numItems)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []T); ok {
		r0 = returnFunc(ctx, numItems)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, numItems)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisPriorityQueue_PopManyAndRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopManyAndRemove'
type RedisPriorityQueue_PopManyAndRemove_Call[T any] struct {
	*mock.Call
}

// PopManyAndRemove is a helper method to define mock.On call
//   - ctx
//   - numItems
func (_e *RedisPriorityQueue_Expecter[T]) PopManyAndRemove(ctx interface{}, numItems interface{}) *RedisPriorityQueue_PopManyAndRemove_Call[T] {
	return &RedisPriorityQueue_PopManyAndRemove_Call[T]{Call: _e.mock.On("PopManyAndRemove", ctx, numItems)}
}

func (_c *RedisPriorityQueue_PopManyAndRemove_Call[T]) Run(run func(ctx context.Context, numItems int)) *RedisPriorityQueue_PopManyAndRemove_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *RedisPriorityQueue_PopManyAndRemove_Call[T]) Return(vs []T, err error) *RedisPriorityQueue_PopManyAndRemove_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *RedisPriorityQueue_PopManyAndRemove_Call[T]) RunAndReturn(run func(ctx context.Context, numItems int) ([]T, error)) *RedisPriorityQueue_PopManyAndRemove_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type RedisPriorityQueue
func (_mock *RedisPriorityQueue[T]) Push(ctx context.Context, item T, priority int) error {
	ret := _mock.Called(ctx, item, priority)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T, int) error); ok {
		r0 = returnFunc(ctx, item, priority)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RedisPriorityQueue_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type RedisPriorityQueue_Push_Call[T any] struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx
//   - item
//   - priority
func (_e *RedisPriorityQueue_Expecter[T]) Push(ctx interface{}, item interface{}, priority interface{}) *RedisPriorityQueue_Push_Call[T] {
	return &RedisPriorityQueue_Push_Call[T]{Call: _e.mock.On("Push", ctx, item, priority)}
}

func (_c *RedisPriorityQueue_Push_Call[T]) Run(run func(ctx context.Context, item T, priority int)) *RedisPriorityQueue_Push_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T), args[2].(int))
	})
	return _c
}

func (_c *RedisPriorityQueue_Push_Call[T]) Return(err error) *RedisPriorityQueue_Push_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *RedisPriorityQueue_Push_Call[T]) RunAndReturn(run func(ctx context.Context, item T, priority int) error) *RedisPriorityQueue_Push_Call[T] {
	_c.Call.Return(run)
	return _c
}
